import type { Collection } from "./types";

/**
 * Collections — curated dish bundles per event type.
 *
 * A collection is the "don't start from scratch" answer to the blank-canvas
 * problem. Users tap "Add Collection to My Event" and get a sensible default
 * they can tweak before requesting a quote.
 *
 * Rules when editing:
 *  - `dishIds` must reference real entries in `dishes.ts`. Validate via
 *    src/lib/content.ts `assertCollectionsAreValid()`.
 *  - One `signature: true` collection per event type. Surfaced first.
 *  - `guestRange` is a guideline — does NOT bind the actual quote.
 */
export const collections: Collection[] = [
  /* ─── WEDDINGS ─────────────────────────────────────────────────────── */
  {
    id: "royal-wedding-collection",
    slug: "royal-wedding-collection",
    name: { en: "Royal Wedding Tasting", ar: "تذوّق الزفاف الملكي" },
    eyebrow: { en: "Signature Wedding", ar: "زفاف مميز" },
    description: {
      en: "Our flagship wedding menu — sixteen dishes across canapés, live stations, signature mains and a kunafa trio finale.",
      ar: "قائمة الزفاف الرئيسية لدينا — ستة عشر طبقاً تشمل الكنابيه والمحطات الحية والأطباق الرئيسية المميزة وثلاثية الكنافة كنهاية.",
    },
    forEventIds: ["weddings"],
    dishIds: [
      "salmon-blinis",
      "gorgonzola-walnut-canapes",
      "prawn-cocktail-bites",
      "spicy-labneh-canapes",
      "classic-hummus-tahini",
      "fattoush-pomegranate",
      "burrata-prosciutto",
      "lamb-ouzi-station",
      "shawarma-live-station",
      "mansaf-meat",
      "grilled-hamour-herbs",
      "saudi-qahwa-cardamom",
      "medjool-dates-selection",
      "creme-brulee-cups",
      "umm-ali-kunafa",
      "kunafa-trio",
    ],
    image: "/images/collections/royal-wedding.webp",
    heroImage: "/images/collections/royal-wedding-hero.webp",
    signature: true,
    guestRange: { min: 200, max: 1000 },
    notes: {
      en: "Includes Arabic coffee ceremony and white-glove service. Live stations require venue power supply.",
      ar: "يشمل مراسم القهوة العربية وخدمة راقية. تتطلب المحطات الحية إمدادات طاقة في المكان.",
    },
  },
  {
    id: "kosha-reception-collection",
    slug: "kosha-reception-collection",
    name: { en: "Kosha Reception", ar: "استقبال الكوشة" },
    eyebrow: { en: "Intimate Wedding", ar: "زفاف حميمي" },
    description: {
      en: "An elegant standing reception — passed canapés, mocktails and a dessert table for the bride's closest circle.",
      ar: "استقبال أنيق واقف — كنابيه تُمرّر، مشروبات منعشة وطاولة حلويات لأقرب دائرة العروس.",
    },
    forEventIds: ["weddings"],
    dishIds: [
      "salmon-blinis",
      "caprese-skewers",
      "tomato-basil-bruschetta",
      "smoked-turkey-mini-rolls",
      "gorgonzola-walnut-canapes",
      "mocktail-station",
      "petit-fours-selection",
      "macarons-assortment",
      "mini-cheesecakes",
      "saudi-qahwa-cardamom",
    ],
    image: "/images/collections/kosha-reception.webp",
    heroImage: "/images/collections/kosha-reception-hero.webp",
    guestRange: { min: 50, max: 200 },
  },
  {
    id: "garden-wedding-collection",
    slug: "garden-wedding-collection",
    name: { en: "Garden Wedding Feast", ar: "وليمة الزفاف في الحديقة" },
    eyebrow: { en: "Outdoor Wedding", ar: "زفاف في الهواء الطلق" },
    description: {
      en: "Open-air dining with the BBQ pit at its centre — live grills, mezze tables and a dessert station under the stars.",
      ar: "طعام في الهواء الطلق مع شواية الفحم في المركز — مشاوي حية، طاولات مزة ومحطة حلويات تحت النجوم.",
    },
    forEventIds: ["weddings"],
    dishIds: [
      "classic-hummus-tahini",
      "muhammara-eggplant",
      "fattoush-pomegranate",
      "tabbouleh-quinoa",
      "bbq-live-station",
      "mixed-grill-station",
      "lamb-arayes",
      "lamb-neck-ribs",
      "saj-bread-station",
      "mocktail-station",
      "umm-ali-kunafa",
      "crepe-dessert-station",
    ],
    image: "/images/collections/garden-wedding.webp",
    heroImage: "/images/collections/garden-wedding-hero.webp",
    guestRange: { min: 100, max: 500 },
  },
  {
    id: "najdi-traditional-wedding-collection",
    slug: "najdi-traditional-wedding-collection",
    name: { en: "Najdi Traditional Wedding", ar: "زفاف نجدي تقليدي" },
    eyebrow: { en: "Heritage Wedding", ar: "زفاف تراثي" },
    description: {
      en: "A celebration rooted in Saudi heritage — jareesh, matbooz, the full Arabic coffee ceremony, and a finale of kunafa and pistachio mahalabia.",
      ar: "احتفال متجذّر في التراث السعودي — جريش، مطبق، مراسم القهوة العربية الكاملة، ونهاية بالكنافة ومهلبية الفستق.",
    },
    forEventIds: ["weddings", "ramadan-eid"],
    dishIds: [
      "spicy-labneh-nuts",
      "muhammara-eggplant",
      "classic-hummus-tahini",
      "saudi-jareesh",
      "matbooz-meat",
      "mansaf-meat",
      "maklouba-chicken",
      "lamb-ouzi-station",
      "mixed-stuffed-vegetables",
      "saudi-qahwa-cardamom",
      "arabic-coffee-saffron",
      "medjool-dates-selection",
      "umm-ali-kunafa",
      "pistachio-pudding",
    ],
    image: "/images/collections/najdi-wedding.webp",
    heroImage: "/images/collections/najdi-wedding-hero.webp",
    guestRange: { min: 150, max: 800 },
    notes: {
      en: "Ground-service majlis seating available on request.",
      ar: "جلسات مجلس بخدمة أرضية متوفرة عند الطلب.",
    },
  },

  /* ─── CORPORATE ────────────────────────────────────────────────────── */
  {
    id: "executive-coffee-break-collection",
    slug: "executive-coffee-break-collection",
    name: { en: "Executive Coffee Break", ar: "استراحة قهوة تنفيذية" },
    eyebrow: { en: "Boardroom Standard", ar: "معيار قاعة الاجتماعات" },
    description: {
      en: "The dependable boardroom break — premium coffee, mini pastries, sandwiches and fresh fruit. Set up in fifteen minutes, cleared in five.",
      ar: "استراحة قاعة الاجتماعات الموثوقة — قهوة فاخرة، معجنات صغيرة، سندويتشات وفواكه طازجة. تُعدّ في خمس عشرة دقيقة وتُرفع في خمس.",
    },
    forEventIds: ["corporate", "government"],
    dishIds: [
      "mini-turkey-baguette",
      "feta-cucumber-baguette",
      "mini-chicken-cheese-quiche",
      "cranberry-pecan-cheese-ball",
      "mini-croissants",
      "french-pastry-platter",
      "seasonal-fruit-cuts",
      "espresso-americano",
      "cappuccino-latte",
      "juice-water-station",
    ],
    image: "/images/collections/executive-coffee-break.webp",
    heroImage: "/images/collections/executive-coffee-break-hero.webp",
    guestRange: { min: 20, max: 150 },
  },
  {
    id: "boardroom-luncheon-collection",
    slug: "boardroom-luncheon-collection",
    name: { en: "Boardroom Luncheon", ar: "غداء قاعة الاجتماعات" },
    eyebrow: { en: "Working Lunch", ar: "غداء عمل" },
    description: {
      en: "A complete sit-down lunch designed to fuel afternoon meetings — light starters, a hot main, fresh salads and a single elegant dessert.",
      ar: "غداء جالس كامل مصمم لتغذية اجتماعات الظهيرة — مقبلات خفيفة، طبق رئيسي ساخن، سلطات طازجة وحلوى أنيقة واحدة.",
    },
    forEventIds: ["corporate"],
    dishIds: [
      "caprese-tomato-pesto",
      "tabbouleh-quinoa",
      "fattoush-pomegranate",
      "classic-hummus-tahini",
      "linguine-al-pesto-chicken",
      "risotto-funghi",
      "shish-tawook-white",
      "grilled-fish-steak",
      "seasonal-fruit-cuts",
      "tiramisu-cake-square",
    ],
    image: "/images/collections/boardroom-luncheon.webp",
    heroImage: "/images/collections/boardroom-luncheon-hero.webp",
    guestRange: { min: 15, max: 80 },
  },
  {
    id: "product-launch-gala-collection",
    slug: "product-launch-gala-collection",
    name: { en: "Product Launch Gala", ar: "حفل إطلاق منتج" },
    eyebrow: { en: "Brand-Forward Event", ar: "فعالية تركز على العلامة" },
    description: {
      en: "A standing reception engineered for networking — twelve canapés, three live stations and a dessert wall that doubles as the photo backdrop.",
      ar: "استقبال واقف مصمم للتواصل — اثني عشر كنابيه، ثلاث محطات حية وجدار حلويات يصلح أيضاً كخلفية للتصوير.",
    },
    forEventIds: ["corporate"],
    dishIds: [
      "salmon-blinis",
      "prawn-cocktail-bites",
      "caprese-skewers",
      "tomato-basil-bruschetta",
      "gorgonzola-walnut-canapes",
      "stuffed-mushrooms",
      "arancini-classic",
      "pasta-action-station",
      "shawarma-live-station",
      "burger-live-station",
      "mocktail-station",
      "petit-fours-selection",
      "macarons-assortment",
      "creme-brulee-cups",
    ],
    image: "/images/collections/product-launch-gala.webp",
    heroImage: "/images/collections/product-launch-gala-hero.webp",
    signature: true,
    guestRange: { min: 100, max: 500 },
  },

  /* ─── VIP RECEPTIONS ───────────────────────────────────────────────── */
  {
    id: "royal-table-collection",
    slug: "royal-table-collection",
    name: { en: "Royal Table", ar: "المائدة الملكية" },
    eyebrow: { en: "Signature VIP", ar: "VIP مميز" },
    description: {
      en: "A tasting of rarity — Beluga caviar, A5 wagyu, white truffle tagliolini, salmon sashimi, lamb ouzi tableside and dessert artistry. Served at one long table.",
      ar: "تذوّق النوادر — كافيار البيلوغا، واغيو A5، تاغليوليني الكمأة البيضاء، ساشيمي السلمون، أوزي الخروف على المائدة وفن الحلويات. تُقدَّم على مائدة واحدة طويلة.",
    },
    forEventIds: ["vip"],
    dishIds: [
      "beluga-caviar-service",
      "salmon-sashimi",
      "tuna-tartare",
      "beef-carpaccio",
      "burrata-prosciutto",
      "salmon-sushi-cake",
      "dragon-rolls",
      "tandoori-prawns",
      "grilled-hamour-herbs",
      "white-truffle-tagliolini",
      "a5-wagyu-tasting",
      "lamb-ouzi-station",
      "saudi-qahwa-cardamom",
      "panna-cotta-berries",
      "kunafa-trio",
    ],
    image: "/images/collections/royal-table.webp",
    heroImage: "/images/collections/royal-table-hero.webp",
    signature: true,
    guestRange: { min: 10, max: 60 },
    notes: {
      en: "Includes NDA, background-checked staff and no-photography protocol.",
      ar: "يشمل اتفاقية عدم إفصاح، طاقم بتحقق خلفية، وبروتوكول عدم تصوير.",
    },
  },
  {
    id: "diplomatic-reception-collection",
    slug: "diplomatic-reception-collection",
    name: { en: "Diplomatic Reception", ar: "استقبال دبلوماسي" },
    eyebrow: { en: "International Hosting", ar: "استضافة دولية" },
    description: {
      en: "A reception calibrated for international palates and dietary protocols — sushi, Mediterranean, Levantine and patisserie, each clearly labelled.",
      ar: "استقبال مُعدّل للأذواق الدولية والبروتوكولات الغذائية — سوشي ومتوسطي وشامي ومعجنات، كل منها موسوم بوضوح.",
    },
    forEventIds: ["vip", "government"],
    dishIds: [
      "salmon-blinis",
      "tuna-tartare",
      "california-rolls",
      "shrimp-cocktail",
      "crab-mango-sesame-salad",
      "spicy-labneh-canapes",
      "burrata-prosciutto",
      "lamb-neck-ribs",
      "petit-fours-selection",
      "saudi-qahwa-cardamom",
    ],
    image: "/images/collections/diplomatic-reception.webp",
    heroImage: "/images/collections/diplomatic-reception-hero.webp",
    guestRange: { min: 30, max: 200 },
  },
  {
    id: "private-residence-collection",
    slug: "private-residence-collection",
    name: { en: "Private Residence Dinner", ar: "عشاء المسكن الخاص" },
    eyebrow: { en: "Home Hosting", ar: "ضيافة منزلية" },
    description: {
      en: "Multi-course in-residence dinner — discreet kitchen brigade, no logo on the vans, served at your table by uniformed staff.",
      ar: "عشاء متعدد الأطباق في المسكن — فرقة مطبخ سرية، بدون شعار على الشاحنات، يُقدَّم على مائدتك بطاقم بزي موحد.",
    },
    forEventIds: ["vip", "private"],
    dishIds: [
      "burrata-prosciutto",
      "beef-carpaccio",
      "spicy-labneh-nuts",
      "muhammara-eggplant",
      "salmon-sushi-cake",
      "grilled-hamour-herbs",
      "linguine-al-pesto-chicken",
      "lamb-ouzal",
      "carving-station",
      "saudi-qahwa-cardamom",
      "creme-brulee-cups",
      "kunafa-trio",
    ],
    image: "/images/collections/private-residence.webp",
    heroImage: "/images/collections/private-residence-hero.webp",
    guestRange: { min: 15, max: 80 },
  },

  /* ─── PRIVATE GATHERINGS ───────────────────────────────────────────── */
  {
    id: "family-majlis-collection",
    slug: "family-majlis-collection",
    name: { en: "Family Majlis Dinner", ar: "عشاء مجلس العائلة" },
    eyebrow: { en: "Signature Private", ar: "خاص مميز" },
    description: {
      en: "The classic Friday family table — mezze, mansaf, mixed grill, kunafa and Arabic coffee. Hosted as you would, but without you lifting a finger.",
      ar: "مائدة العائلة الكلاسيكية ليوم الجمعة — مزة، منسف، مشاوي مشكلة، كنافة وقهوة عربية. تُستضاف كما تفعل أنت، لكن بدون أن ترفع إصبعاً.",
    },
    forEventIds: ["private", "ramadan-eid"],
    dishIds: [
      "classic-hummus-tahini",
      "muhammara-eggplant",
      "spicy-labneh-nuts",
      "tabbouleh-quinoa",
      "fattoush-pomegranate",
      "mixed-grill-station",
      "mansaf-meat",
      "lamb-arayes",
      "saj-bread-station",
      "saudi-qahwa-cardamom",
      "medjool-dates-selection",
      "kunafa-trio",
    ],
    image: "/images/collections/family-majlis.webp",
    heroImage: "/images/collections/family-majlis-hero.webp",
    signature: true,
    guestRange: { min: 20, max: 150 },
  },
  {
    id: "villa-engagement-collection",
    slug: "villa-engagement-collection",
    name: { en: "Villa Engagement Party", ar: "حفل خطوبة الفيلا" },
    eyebrow: { en: "Engagement", ar: "خطوبة" },
    description: {
      en: "A polished celebration in your garden or majlis — canapé hour, live stations, mocktail bar and a celebration cake.",
      ar: "احتفال راقٍ في حديقتك أو مجلسك — ساعة كنابيه، محطات حية، بار مشروبات وكيك احتفال.",
    },
    forEventIds: ["private"],
    dishIds: [
      "salmon-blinis",
      "caprese-skewers",
      "prawn-cocktail-bites",
      "tomato-basil-bruschetta",
      "shawarma-live-station",
      "pasta-action-station",
      "mocktail-station",
      "saudi-qahwa-cardamom",
      "mini-fruit-tarts",
      "chocolate-cake-classic",
      "macarons-assortment",
      "mini-cheesecakes",
    ],
    image: "/images/collections/villa-engagement.webp",
    heroImage: "/images/collections/villa-engagement-hero.webp",
    guestRange: { min: 30, max: 200 },
  },
  {
    id: "anniversary-dinner-collection",
    slug: "anniversary-dinner-collection",
    name: { en: "Anniversary Dinner", ar: "عشاء الذكرى السنوية" },
    eyebrow: { en: "Intimate Plated", ar: "عشاء حميمي مرتّب" },
    description: {
      en: "A plated dinner for the closest people — three courses, paired mocktails, panna cotta to close. Service ends with Arabic coffee in the garden.",
      ar: "عشاء مرتّب للأقربين — ثلاثة أطباق، مشروبات منسّقة، بانا كوتا للختام. تنتهي الخدمة بالقهوة العربية في الحديقة.",
    },
    forEventIds: ["private"],
    dishIds: [
      "burrata-prosciutto",
      "tuna-tartare",
      "beef-carpaccio",
      "salmon-sashimi",
      "risotto-funghi",
      "grilled-hamour-herbs",
      "panna-cotta-berries",
      "petit-fours-selection",
      "saudi-qahwa-cardamom",
      "mocktail-station",
    ],
    image: "/images/collections/anniversary-dinner.webp",
    heroImage: "/images/collections/anniversary-dinner-hero.webp",
    guestRange: { min: 10, max: 40 },
  },

  /* ─── BIRTHDAYS ────────────────────────────────────────────────────── */
  {
    id: "kids-birthday-collection",
    slug: "kids-birthday-collection",
    name: { en: "Kids Birthday Celebration", ar: "احتفال عيد ميلاد الأطفال" },
    eyebrow: { en: "Ages 4–12", ar: "للأعمار 4–12" },
    description: {
      en: "Mini burgers, pizza slices, chicken nuggets, a chocolate fountain and a candy corner — finished with a chocolate-stuffed birthday cake.",
      ar: "برغر صغير، شرائح بيتزا، قطع دجاج، نافورة شوكولاتة وركن حلوى — تنتهي بكيكة عيد ميلاد محشوة بالشوكولاتة.",
    },
    forEventIds: ["birthdays"],
    dishIds: [
      "burger-live-station",
      "margherita-flatbread",
      "beef-burger-grilled",
      "mini-quiche-lorraine",
      "seasonal-fruit-cuts",
      "crepe-dessert-station",
      "mini-cheesecakes",
      "mini-chocolate-eclairs",
      "chocolate-cake-classic",
      "juice-water-station",
    ],
    image: "/images/collections/kids-birthday.webp",
    heroImage: "/images/collections/kids-birthday-hero.webp",
    guestRange: { min: 10, max: 100 },
  },
  {
    id: "milestone-birthday-collection",
    slug: "milestone-birthday-collection",
    name: { en: "Milestone Birthday", ar: "عيد ميلاد المحطة المهمة" },
    eyebrow: { en: "Signature Birthday", ar: "عيد ميلاد مميز" },
    description: {
      en: "For the 30th, 40th, 50th — a grown-up celebration with canapés, sushi, mixed grill, mocktails and a dessert finale worth a photograph.",
      ar: "للعقد الثالث والرابع والخامس — احتفال راقٍ مع كنابيه وسوشي ومشاوي مشكلة ومشروبات ونهاية حلويات تستحق صورة.",
    },
    forEventIds: ["birthdays"],
    dishIds: [
      "salmon-blinis",
      "prawn-cocktail-bites",
      "caprese-skewers",
      "california-rolls",
      "spicy-tuna-rolls",
      "mixed-grill-station",
      "pasta-action-station",
      "mocktail-station",
      "chocolate-cake-classic",
      "macarons-assortment",
      "mini-cheesecakes",
      "kunafa-trio",
    ],
    image: "/images/collections/milestone-birthday.webp",
    heroImage: "/images/collections/milestone-birthday-hero.webp",
    signature: true,
    guestRange: { min: 40, max: 200 },
  },
  {
    id: "sweet-sixteen-collection",
    slug: "sweet-sixteen-collection",
    name: { en: "Sweet Sixteen", ar: "ستة عشر الحلوة" },
    eyebrow: { en: "Teen Celebration", ar: "احتفال المراهقين" },
    description: {
      en: "Sushi rolls, sliders, pasta station, mocktail bar and a dessert wall — designed for the phone camera as much as the palate.",
      ar: "رولات سوشي، سلايدر، محطة معكرونة، بار مشروبات وجدار حلويات — مصمّم لكاميرا الهاتف بقدر اهتمامه بالذوق.",
    },
    forEventIds: ["birthdays"],
    dishIds: [
      "california-rolls",
      "dragon-rolls",
      "burger-live-station",
      "pasta-action-station",
      "mocktail-station",
      "crepe-dessert-station",
      "macarons-assortment",
      "mini-cheesecakes",
      "chocolate-cake-classic",
      "mini-chocolate-eclairs",
    ],
    image: "/images/collections/sweet-sixteen.webp",
    heroImage: "/images/collections/sweet-sixteen-hero.webp",
    guestRange: { min: 20, max: 100 },
  },

  /* ─── RAMADAN & EID ────────────────────────────────────────────────── */
  {
    id: "ramadan-iftar-collection",
    slug: "ramadan-iftar-collection",
    name: { en: "Ramadan Iftar Table", ar: "مائدة إفطار رمضان" },
    eyebrow: { en: "Signature Ramadan", ar: "رمضان مميز" },
    description: {
      en: "The full Iftar arc — dates and coffee at maghrib, mezze, soup, mains and a desserts finale. Service begins precisely at the call to prayer.",
      ar: "قوس الإفطار الكامل — تمور وقهوة عند المغرب، مزة، شوربة، أطباق رئيسية ونهاية الحلويات. تبدأ الخدمة بدقة عند الأذان.",
    },
    forEventIds: ["ramadan-eid"],
    dishIds: [
      "medjool-dates-selection",
      "saudi-qahwa-cardamom",
      "classic-hummus-tahini",
      "muhammara-eggplant",
      "spicy-labneh-nuts",
      "fattoush-pomegranate",
      "meat-cheese-sambousa",
      "cheese-borek",
      "shawarma-live-station",
      "mansaf-meat",
      "matbooz-meat",
      "saudi-jareesh",
      "qatayef-assortment",
      "umm-ali-kunafa",
      "kunafa-trio",
    ],
    image: "/images/collections/ramadan-iftar.webp",
    heroImage: "/images/collections/ramadan-iftar-hero.webp",
    signature: true,
    guestRange: { min: 30, max: 500 },
    notes: {
      en: "Book at least 4 weeks before Ramadan — capacity sells out by mid-Sha'ban.",
      ar: "احجز قبل رمضان بـ4 أسابيع على الأقل — تنفد السعة بحلول منتصف شعبان.",
    },
  },
  {
    id: "corporate-ramadan-tent-collection",
    slug: "corporate-ramadan-tent-collection",
    name: { en: "Corporate Ramadan Tent", ar: "خيمة رمضان المؤسسية" },
    eyebrow: { en: "Branded Iftar", ar: "إفطار بعلامتك التجارية" },
    description: {
      en: "Branded Iftar tent for clients and partners — light mezze, two stations, dates ceremony, kunafa and gahwa to close.",
      ar: "خيمة إفطار بعلامتك التجارية للعملاء والشركاء — مزة خفيفة، محطتان، مراسم التمور، كنافة وقهوة للختام.",
    },
    forEventIds: ["ramadan-eid", "corporate"],
    dishIds: [
      "medjool-dates-selection",
      "saudi-qahwa-cardamom",
      "classic-hummus-tahini",
      "tabbouleh-quinoa",
      "fattoush-pomegranate",
      "meat-cheese-sambousa",
      "shawarma-live-station",
      "mixed-grill-station",
      "matbooz-meat",
      "baklava-assortment",
      "kunafa-trio",
      "petit-fours-selection",
    ],
    image: "/images/collections/corporate-ramadan-tent.webp",
    heroImage: "/images/collections/corporate-ramadan-tent-hero.webp",
    guestRange: { min: 50, max: 400 },
  },
  {
    id: "eid-family-feast-collection",
    slug: "eid-family-feast-collection",
    name: { en: "Eid Family Feast", ar: "وليمة العيد العائلية" },
    eyebrow: { en: "Eid Hosting", ar: "ضيافة العيد" },
    description: {
      en: "The post-Ramadan family table — generous mezze, two roasted mains, sweet tray and a dedicated children's spread.",
      ar: "مائدة العائلة بعد رمضان — مزة سخية، طبقان رئيسيان مشويان، صينية حلويات وطاولة خاصة بالأطفال.",
    },
    forEventIds: ["ramadan-eid", "private"],
    dishIds: [
      "classic-hummus-tahini",
      "muhammara-eggplant",
      "spicy-labneh-nuts",
      "tabbouleh-quinoa",
      "lamb-ouzi-station",
      "mansaf-meat",
      "shawarma-beetroot-rice",
      "mixed-stuffed-vegetables",
      "kebbeh-yogurt-coriander",
      "saudi-qahwa-cardamom",
      "medjool-dates-selection",
      "baklava-assortment",
      "umm-ali-kunafa",
      "pistachio-pudding",
    ],
    image: "/images/collections/eid-family-feast.webp",
    heroImage: "/images/collections/eid-family-feast-hero.webp",
    guestRange: { min: 25, max: 200 },
  },

  /* ─── GOVERNMENT ───────────────────────────────────────────────────── */
  {
    id: "ministry-reception-collection",
    slug: "ministry-reception-collection",
    name: { en: "Ministry Reception", ar: "استقبال وزاري" },
    eyebrow: { en: "Official Hosting", ar: "استضافة رسمية" },
    description: {
      en: "A protocol-aware reception — Arabic coffee ceremony, mezze, two warm stations and a dignified dessert offering.",
      ar: "استقبال واعٍ للبروتوكول — مراسم القهوة العربية، مزة، محطتان دافئتان وعرض حلويات مهيب.",
    },
    forEventIds: ["government"],
    dishIds: [
      "saudi-qahwa-cardamom",
      "arabic-coffee-saffron",
      "medjool-dates-selection",
      "classic-hummus-tahini",
      "spicy-labneh-nuts",
      "tabbouleh-quinoa",
      "mixed-grill-station",
      "matbooz-meat",
      "baklava-assortment",
      "umm-ali-kunafa",
    ],
    image: "/images/collections/ministry-reception.webp",
    heroImage: "/images/collections/ministry-reception-hero.webp",
    guestRange: { min: 50, max: 300 },
  },
  {
    id: "state-banquet-collection",
    slug: "state-banquet-collection",
    name: { en: "State Banquet", ar: "مأدبة الدولة" },
    eyebrow: { en: "Signature Government", ar: "حكومي مميز" },
    description: {
      en: "Full-protocol banquet — fourteen courses spanning heritage Saudi cuisine and international dishes for visiting delegations.",
      ar: "مأدبة بالبروتوكول الكامل — أربعة عشر طبقاً تمتد من المطبخ السعودي التراثي إلى الأطباق الدولية للوفود الزائرة.",
    },
    forEventIds: ["government"],
    dishIds: [
      "arabic-coffee-saffron",
      "medjool-dates-selection",
      "spicy-labneh-nuts",
      "muhammara-eggplant",
      "classic-hummus-tahini",
      "burrata-prosciutto",
      "saudi-jareesh",
      "mansaf-meat",
      "kabsa-chicken",
      "lamb-ouzi-station",
      "grilled-hamour-herbs",
      "carving-station",
      "umm-ali-kunafa",
      "kunafa-trio",
    ],
    image: "/images/collections/state-banquet.webp",
    heroImage: "/images/collections/state-banquet-hero.webp",
    signature: true,
    guestRange: { min: 80, max: 600 },
    notes: {
      en: "Security-cleared staff, full protocol training, written minute-by-minute run-of-show.",
      ar: "طاقم بتصاريح أمنية، تدريب بروتوكول كامل، جدول عرض مكتوب بالدقيقة.",
    },
  },
  {
    id: "delegation-luncheon-collection",
    slug: "delegation-luncheon-collection",
    name: { en: "Delegation Luncheon", ar: "غداء الوفد" },
    eyebrow: { en: "Working Lunch", ar: "غداء عمل رسمي" },
    description: {
      en: "A working lunch for foreign delegations — balanced between Saudi heritage and international familiarity, served in sequence within an hour.",
      ar: "غداء عمل للوفود الأجنبية — متوازن بين التراث السعودي والمألوف الدولي، يُقدَّم بالتسلسل خلال ساعة.",
    },
    forEventIds: ["government", "corporate"],
    dishIds: [
      "saudi-qahwa-cardamom",
      "medjool-dates-selection",
      "classic-hummus-tahini",
      "fattoush-pomegranate",
      "burrata-prosciutto",
      "linguine-al-pesto-chicken",
      "matbooz-meat",
      "grilled-fish-steak",
      "creme-brulee-cups",
      "petit-fours-selection",
    ],
    image: "/images/collections/delegation-luncheon.webp",
    heroImage: "/images/collections/delegation-luncheon-hero.webp",
    guestRange: { min: 20, max: 80 },
  },
];

export const collectionIds = collections.map((c) => c.id);
