import type { Dish } from "./types";

/**
 * Dish catalog — flat list. ~100 dishes across 9 categories.
 *
 * Editing rules:
 *  - `id` is the stable key. Never rename. If a dish is discontinued, remove
 *    it and let MyEvent state's schema-version check sweep stale references.
 *  - `image` paths follow `/images/dishes/{id}.webp`. Drop assets there.
 *  - Descriptions stay under ~140 chars per locale. Tight reads well.
 *  - No prices, calories, weights, allergens-as-data. Allergen notes go in
 *    descriptions when material to the eater (e.g., "with sesame seeds").
 */
export const dishes: Dish[] = [
  /* ─── FINGER FOOD ──────────────────────────────────────────────────── */
  {
    id: "salmon-blinis",
    slug: "salmon-blinis",
    categoryId: "finger-food",
    name: { en: "Salmon Blinis with Cream Cheese", ar: "بليني السلمون بجبن الكريمة" },
    description: {
      en: "Russian buckwheat blinis topped with cold-smoked salmon, whipped cream cheese and fresh dill.",
      ar: "بليني روسي من الحنطة السوداء مع سلمون مدخن بارد وجبن كريمة وشبت طازج.",
    },
    image: "/images/dishes/salmon-blinis.webp",
    servingStyle: "passed",
    tags: ["seafood", "cold", "signature", "international"],
    recommendedFor: ["weddings", "vip", "corporate"],
    signature: true,
  },
  {
    id: "tomato-basil-bruschetta",
    slug: "tomato-basil-bruschetta",
    categoryId: "finger-food",
    name: { en: "Tomato & Basil Bruschetta", ar: "بروشيتا الطماطم والريحان" },
    description: {
      en: "Toasted sourdough crowned with marinated tomato concassé, basil and aged balsamic.",
      ar: "خبز عجين مقرمش مع طماطم متبّلة وريحان وخل بلسمي معتّق.",
    },
    image: "/images/dishes/tomato-basil-bruschetta.webp",
    servingStyle: "passed",
    tags: ["vegetarian", "cold", "international"],
    recommendedFor: ["weddings", "corporate", "private"],
  },
  {
    id: "caprese-skewers",
    slug: "caprese-skewers",
    categoryId: "finger-food",
    name: { en: "Caprese Skewers", ar: "أسياخ كابريزي" },
    description: {
      en: "Cherry tomato, bocconcini and basil leaf on a bamboo skewer with pesto drizzle.",
      ar: "طماطم كرزية وبوكونشيني وأوراق ريحان على سيخ خيزران مع لمسة من البيستو.",
    },
    image: "/images/dishes/caprese-skewers.webp",
    servingStyle: "passed",
    tags: ["vegetarian", "cold", "international"],
    recommendedFor: ["weddings", "corporate", "private", "birthdays"],
  },
  {
    id: "prawn-cocktail-bites",
    slug: "prawn-cocktail-bites",
    categoryId: "finger-food",
    name: { en: "Prawn Cocktail Bites", ar: "لقمات كوكتيل الروبيان" },
    description: {
      en: "Poached king prawn in a crisp pastry shell with marie-rose sauce and lemon zest.",
      ar: "روبيان ملكي مسلوق في قشرة معجنات هشة مع صلصة ماري-روز وقشر الليمون.",
    },
    image: "/images/dishes/prawn-cocktail-bites.webp",
    servingStyle: "passed",
    tags: ["seafood", "cold", "signature"],
    recommendedFor: ["vip", "weddings", "corporate"],
  },
  {
    id: "chicken-samosa-mini",
    slug: "chicken-samosa-mini",
    categoryId: "finger-food",
    name: { en: "Mini Chicken Samosas", ar: "سمبوسة الدجاج الصغيرة" },
    description: {
      en: "Hand-folded pastry parcels with spiced chicken, fresh coriander and tamarind dip.",
      ar: "سمبوسة محضّرة يدوياً بحشوة الدجاج المتبّل والكزبرة الطازجة مع صلصة التمر الهندي.",
    },
    image: "/images/dishes/chicken-samosa-mini.webp",
    servingStyle: "passed",
    tags: ["hot"],
    recommendedFor: ["ramadan-eid", "private", "corporate"],
  },
  {
    id: "cheese-borek",
    slug: "cheese-borek",
    categoryId: "finger-food",
    name: { en: "Cheese Borek", ar: "بوريك الجبن" },
    description: {
      en: "Crisp filo rolls filled with akkawi and halloumi, baked until golden.",
      ar: "لفائف فيلو مقرمشة محشوّة بجبن العكاوي والحلوم، مخبوزة حتى الذهبي.",
    },
    image: "/images/dishes/cheese-borek.webp",
    servingStyle: "passed",
    tags: ["vegetarian", "hot"],
    recommendedFor: ["ramadan-eid", "private", "corporate"],
  },
  {
    id: "meat-spring-rolls",
    slug: "meat-spring-rolls",
    categoryId: "finger-food",
    name: { en: "Meat Spring Rolls", ar: "لفائف اللحم" },
    description: {
      en: "Crispy wheat-pastry rolls with marinated beef, cabbage and ginger, served with sweet chilli.",
      ar: "لفائف عجين مقرمشة بحشوة لحم البقر المتبّل والملفوف والزنجبيل مع صلصة الفلفل الحلو.",
    },
    image: "/images/dishes/meat-spring-rolls.webp",
    servingStyle: "passed",
    tags: ["hot"],
    recommendedFor: ["private", "corporate", "weddings"],
  },
  {
    id: "mini-quiche-lorraine",
    slug: "mini-quiche-lorraine",
    categoryId: "finger-food",
    name: { en: "Mini Quiche Lorraine", ar: "كيش لورين الصغير" },
    description: {
      en: "Buttery shortcrust tart with smoked turkey, gruyère and herb custard.",
      ar: "تارت زبدي مع ديك رومي مدخن وجبن غرويير وكاسترد بالأعشاب.",
    },
    image: "/images/dishes/mini-quiche-lorraine.webp",
    servingStyle: "passed",
    tags: ["hot", "international"],
    recommendedFor: ["corporate", "weddings", "private"],
  },
  {
    id: "stuffed-mushrooms",
    slug: "stuffed-mushrooms",
    categoryId: "finger-food",
    name: { en: "Stuffed Mushrooms", ar: "الفطر المحشي" },
    description: {
      en: "Roasted button mushrooms with garlic-herb cream cheese and crispy panko crust.",
      ar: "فطر محمّص بحشوة جبن الكريمة بالثوم والأعشاب وقشرة البانكو المقرمشة.",
    },
    image: "/images/dishes/stuffed-mushrooms.webp",
    servingStyle: "passed",
    tags: ["vegetarian", "hot"],
    recommendedFor: ["private", "corporate", "weddings"],
  },
  {
    id: "spicy-labneh-canapes",
    slug: "spicy-labneh-canapes",
    categoryId: "finger-food",
    name: { en: "Spicy Labneh Canapés with Nuts", ar: "كنابيه اللبنة الحارة بالمكسرات" },
    description: {
      en: "Strained yogurt with chilli oil, dukkah and toasted pistachios on a sesame crisp.",
      ar: "لبنة مصفّاة مع زيت الفلفل والدقة والفستق المحمّص على بسكويت السمسم.",
    },
    image: "/images/dishes/spicy-labneh-canapes.webp",
    servingStyle: "passed",
    tags: ["vegetarian", "cold", "spicy", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "government"],
  },
  {
    id: "gorgonzola-walnut-canapes",
    slug: "gorgonzola-walnut-canapes",
    categoryId: "finger-food",
    name: { en: "Gorgonzola & Walnut Canapés", ar: "كنابيه الغورغونزولا والجوز" },
    description: {
      en: "Italian blue cheese with caramelised walnut, honey drizzle and fig compote on rye.",
      ar: "جبن أزرق إيطالي مع جوز مكرمل ولمسة عسل ومربى التين على خبز الجاودار.",
    },
    image: "/images/dishes/gorgonzola-walnut-canapes.webp",
    servingStyle: "passed",
    tags: ["vegetarian", "cold", "signature"],
    recommendedFor: ["vip", "weddings", "corporate"],
  },
  {
    id: "smoked-turkey-mini-rolls",
    slug: "smoked-turkey-mini-rolls",
    categoryId: "finger-food",
    name: { en: "Smoked Turkey Mini Rolls", ar: "لفائف الديك الرومي المدخن" },
    description: {
      en: "Soft brioche rolls layered with smoked turkey breast, rocket and dijon cream.",
      ar: "لفائف بريوش طرية مع صدر ديك رومي مدخن وجرجير وكريمة الديجون.",
    },
    image: "/images/dishes/smoked-turkey-mini-rolls.webp",
    servingStyle: "passed",
    tags: ["cold"],
    recommendedFor: ["corporate", "private", "birthdays"],
  },

  /* ─── COFFEE BREAK ─────────────────────────────────────────────────── */
  {
    id: "mini-turkey-baguette",
    slug: "mini-turkey-baguette",
    categoryId: "coffee-break",
    name: { en: "Mini Turkey Baguette", ar: "باجيت صغير بالديك الرومي" },
    description: {
      en: "Petite milk-bread baguette with smoked turkey and pickled cucumber.",
      ar: "باجيت صغير من خبز الحليب مع ديك رومي مدخن وخيار مخلل.",
    },
    image: "/images/dishes/mini-turkey-baguette.webp",
    servingStyle: "buffet",
    tags: ["cold"],
    recommendedFor: ["corporate", "government", "private"],
  },
  {
    id: "feta-cucumber-baguette",
    slug: "feta-cucumber-baguette",
    categoryId: "coffee-break",
    name: { en: "Feta & Cucumber Baguette", ar: "باجيت الفيتا والخيار" },
    description: {
      en: "Mini baguette with creamy feta, fresh cucumber and a touch of mint oil.",
      ar: "باجيت صغير مع جبن الفيتا الكريمي والخيار الطازج ولمسة من زيت النعناع.",
    },
    image: "/images/dishes/feta-cucumber-baguette.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold"],
    recommendedFor: ["corporate", "government", "private"],
  },
  {
    id: "tuna-olive-rolls",
    slug: "tuna-olive-rolls",
    categoryId: "coffee-break",
    name: { en: "Tuna & Sweetcorn Olive Rolls", ar: "لفائف التونة والذرة بالزيتون" },
    description: {
      en: "Olive-studded mini rolls filled with tuna mayonnaise, sweetcorn and chives.",
      ar: "لفائف صغيرة بالزيتون محشوّة بالتونة بالمايونيز والذرة الحلوة والثوم المعمر.",
    },
    image: "/images/dishes/tuna-olive-rolls.webp",
    servingStyle: "buffet",
    tags: ["seafood", "cold"],
    recommendedFor: ["corporate", "government"],
  },
  {
    id: "cucumber-feta-shrimp-roll",
    slug: "cucumber-feta-shrimp-roll",
    categoryId: "coffee-break",
    name: { en: "Cucumber, Feta & Shrimp Roll", ar: "لفائف الخيار والفيتا والروبيان" },
    description: {
      en: "Ribboned cucumber rolled around feta cream and a poached shrimp.",
      ar: "شرائح خيار ملفوفة حول كريمة الفيتا وروبيان مسلوق.",
    },
    image: "/images/dishes/cucumber-feta-shrimp-roll.webp",
    servingStyle: "buffet",
    tags: ["seafood", "cold"],
    recommendedFor: ["corporate", "vip"],
  },
  {
    id: "cranberry-pecan-cheese-ball",
    slug: "cranberry-pecan-cheese-ball",
    categoryId: "coffee-break",
    name: { en: "Cranberry-Pecan Cheese Ball", ar: "كرة الجبن بالتوت البري والبقان" },
    description: {
      en: "Cream cheese sphere rolled in dried cranberry and candied pecan.",
      ar: "كرة جبن كريمي ملفوفة بالتوت البري المجفف والبقان المسكّر.",
    },
    image: "/images/dishes/cranberry-pecan-cheese-ball.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold"],
    recommendedFor: ["corporate", "private"],
  },
  {
    id: "mini-chicken-cheese-quiche",
    slug: "mini-chicken-cheese-quiche",
    categoryId: "coffee-break",
    name: { en: "Mini Chicken & Cheese Quiche", ar: "كيش الدجاج والجبن الصغير" },
    description: {
      en: "Tartlet shells with chicken, cheddar and a touch of thyme.",
      ar: "قوالب تارت صغيرة بالدجاج والشيدر ولمسة من الزعتر.",
    },
    image: "/images/dishes/mini-chicken-cheese-quiche.webp",
    servingStyle: "buffet",
    tags: ["hot"],
    recommendedFor: ["corporate", "government"],
  },
  {
    id: "meat-cheese-sambousa",
    slug: "meat-cheese-sambousa",
    categoryId: "coffee-break",
    name: { en: "Meat & Cheese Sambousa", ar: "سمبوسة اللحم والجبن" },
    description: {
      en: "Crisp triangular pastry with spiced minced beef and stringy mozzarella.",
      ar: "سمبوسة مثلثة مقرمشة بحشوة لحم البقر المتبّل والموزاريلا.",
    },
    image: "/images/dishes/meat-cheese-sambousa.webp",
    servingStyle: "buffet",
    tags: ["hot", "saudi"],
    recommendedFor: ["ramadan-eid", "corporate", "private"],
  },
  {
    id: "french-pastry-platter",
    slug: "french-pastry-platter",
    categoryId: "coffee-break",
    name: { en: "Assorted French Pastry", ar: "تشكيلة المعجنات الفرنسية" },
    description: {
      en: "Pain au chocolat, almond croissant, palmier and chausson aux pommes.",
      ar: "بين أو شوكولا، كرواسون باللوز، بلميه، وشوصون بالتفاح.",
    },
    image: "/images/dishes/french-pastry-platter.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "international"],
    recommendedFor: ["corporate", "government", "vip"],
  },
  {
    id: "danish-pastry-platter",
    slug: "danish-pastry-platter",
    categoryId: "coffee-break",
    name: { en: "Assorted Danish Pastry", ar: "تشكيلة المعجنات الدنماركية" },
    description: {
      en: "Custard, apricot, cinnamon swirl and berry pinwheel danishes.",
      ar: "دنماركيات الكاسترد والمشمش وقرفة لولبية وتوت.",
    },
    image: "/images/dishes/danish-pastry-platter.webp",
    servingStyle: "buffet",
    tags: ["vegetarian"],
    recommendedFor: ["corporate", "government"],
  },
  {
    id: "mini-croissants",
    slug: "mini-croissants",
    categoryId: "coffee-break",
    name: { en: "Mini Butter Croissants", ar: "كرواسون زبدة صغير" },
    description: {
      en: "Hand-laminated mini croissants, baked the morning of your event.",
      ar: "كرواسون صغير مصنوع يدوياً، يُخبز صباح فعاليتك.",
    },
    image: "/images/dishes/mini-croissants.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "signature"],
    recommendedFor: ["corporate", "government", "vip"],
  },
  {
    id: "seasonal-fruit-cuts",
    slug: "seasonal-fruit-cuts",
    categoryId: "coffee-break",
    name: { en: "Seasonal Fresh-Cut Fruits", ar: "فواكه طازجة موسمية" },
    description: {
      en: "Watermelon, melon, pineapple, kiwi, berries and grapes — arranged on ice.",
      ar: "بطيخ وشمام وأناناس وكيوي وتوت وعنب — مرتّبة على الثلج.",
    },
    image: "/images/dishes/seasonal-fruit-cuts.webp",
    servingStyle: "buffet",
    tags: ["vegan", "cold", "gluten-free", "dairy-free"],
    recommendedFor: ["corporate", "ramadan-eid", "government", "private"],
  },
  {
    id: "juice-water-station",
    slug: "juice-water-station",
    categoryId: "coffee-break",
    name: { en: "Assorted Juices & Mineral Water", ar: "عصائر متنوعة ومياه معدنية" },
    description: {
      en: "Orange, apple, mango, cranberry and still/sparkling water — chilled.",
      ar: "برتقال وتفاح ومانجو وتوت بري، ومياه معدنية ساكنة وغازية — مبرّدة.",
    },
    image: "/images/dishes/juice-water-station.webp",
    servingStyle: "buffet",
    tags: ["vegan", "cold"],
    recommendedFor: ["corporate", "government", "private"],
  },

  /* ─── LIVE COOKING STATIONS ────────────────────────────────────────── */
  {
    id: "bbq-live-station",
    slug: "bbq-live-station",
    categoryId: "live-stations",
    name: { en: "BBQ Live Station", ar: "محطة المشاوي الحية" },
    description: {
      en: "Open-flame grill — lamb ouzal, kebabs, shish tawook and fish sabach, served with tahini and rocket.",
      ar: "شواية مفتوحة — أوزال الخروف والكباب وشيش طاووق وسمك صباح، مع الطحينة والجرجير.",
    },
    image: "/images/dishes/bbq-live-station.webp",
    servingStyle: "station",
    tags: ["hot", "signature", "saudi"],
    recommendedFor: ["weddings", "private", "ramadan-eid"],
    signature: true,
  },
  {
    id: "shawarma-live-station",
    slug: "shawarma-live-station",
    categoryId: "live-stations",
    name: { en: "Shawarma Live Station", ar: "محطة الشاورما الحية" },
    description: {
      en: "Vertical spit lamb and chicken shaved to order with garlic sauce, pickles and saj bread.",
      ar: "لحم وشاورما دجاج تُقطّع طلباً مع ثومية ومخللات وخبز الصاج.",
    },
    image: "/images/dishes/shawarma-live-station.webp",
    servingStyle: "station",
    tags: ["hot", "signature", "saudi"],
    recommendedFor: ["weddings", "private", "corporate", "ramadan-eid"],
    signature: true,
  },
  {
    id: "burger-live-station",
    slug: "burger-live-station",
    categoryId: "live-stations",
    name: { en: "BBQ Burger Live Station", ar: "محطة برغر الباربيكيو الحية" },
    description: {
      en: "Smashed beef and chicken sliders, melted cheddar, caramelised onion and house BBQ sauce.",
      ar: "سلايدر لحم بقر ودجاج، جبن شيدر ذائب، بصل مكرمل وصلصة باربيكيو خاصة.",
    },
    image: "/images/dishes/burger-live-station.webp",
    servingStyle: "station",
    tags: ["hot", "international"],
    recommendedFor: ["birthdays", "private", "corporate"],
  },
  {
    id: "lamb-ouzi-station",
    slug: "lamb-ouzi-station",
    categoryId: "live-stations",
    name: { en: "Whole Lamb Ouzi Station", ar: "محطة الأوزي بالخروف الكامل" },
    description: {
      en: "Slow-roasted whole lamb on saffron rice with raisins and toasted almonds — carved tableside.",
      ar: "خروف كامل مشوي على الطريقة البطيئة فوق أرز الزعفران مع الزبيب واللوز المحمّص — يُقطّع على المائدة.",
    },
    image: "/images/dishes/lamb-ouzi-station.webp",
    servingStyle: "tableside",
    tags: ["hot", "signature", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "vip", "government"],
    signature: true,
  },
  {
    id: "pasta-action-station",
    slug: "pasta-action-station",
    categoryId: "live-stations",
    name: { en: "Pasta Action Station", ar: "محطة المعكرونة التفاعلية" },
    description: {
      en: "Fresh penne, fettuccine and rigatoni — tossed to order with five sauces and guest choice of proteins.",
      ar: "بيني وفيتوتشيني وريغاتوني طازجة — تُحضّر طلباً بخمس صلصات وخيارات بروتين متعددة.",
    },
    image: "/images/dishes/pasta-action-station.webp",
    servingStyle: "station",
    tags: ["hot", "international"],
    recommendedFor: ["corporate", "weddings", "birthdays"],
  },
  {
    id: "mixed-grill-station",
    slug: "mixed-grill-station",
    categoryId: "live-stations",
    name: { en: "Mixed Grill Station", ar: "محطة المشاوي المشكلة" },
    description: {
      en: "Lamb chops, beef tenderloin medallions, chicken tikka and prawn skewers — flame-grilled to order.",
      ar: "ريش غنم، ميداليون لحم بقر، تكا دجاج وأسياخ روبيان — تُشوى على اللهب طلباً.",
    },
    image: "/images/dishes/mixed-grill-station.webp",
    servingStyle: "station",
    tags: ["hot", "signature"],
    recommendedFor: ["weddings", "vip", "private"],
  },
  {
    id: "omelette-station",
    slug: "omelette-station",
    categoryId: "live-stations",
    name: { en: "Omelette Live Station", ar: "محطة الأومليت الحية" },
    description: {
      en: "Custom omelettes with chicken, mushroom, smoked beef pastrami, basturma, onion, parsley and tomato.",
      ar: "أومليت حسب الطلب مع دجاج وفطر وبسطرمة ولحم بقر مدخن وبصل وبقدونس وطماطم.",
    },
    image: "/images/dishes/omelette-station.webp",
    servingStyle: "station",
    tags: ["hot"],
    recommendedFor: ["corporate", "private", "ramadan-eid"],
  },
  {
    id: "saj-bread-station",
    slug: "saj-bread-station",
    categoryId: "live-stations",
    name: { en: "Saj Bread Station", ar: "محطة خبز الصاج" },
    description: {
      en: "Hot saj bread baked on a domed griddle — served with za'atar, labneh, halloumi and Nutella.",
      ar: "خبز صاج طازج يُخبز على القبة — يُقدَّم مع الزعتر واللبنة والحلوم والنوتيلا.",
    },
    image: "/images/dishes/saj-bread-station.webp",
    servingStyle: "station",
    tags: ["vegetarian", "hot", "saudi"],
    recommendedFor: ["ramadan-eid", "weddings", "private"],
  },
  {
    id: "carving-station",
    slug: "carving-station",
    categoryId: "live-stations",
    name: { en: "Carving Station", ar: "محطة نحت اللحوم" },
    description: {
      en: "Roast beef striploin or whole lamb leg — sliced to order with horseradish and red wine jus.",
      ar: "خاصرة لحم بقر مشوية أو فخذ خروف كامل — تُقطّع طلباً مع الفجل الحار وصلصة النبيذ الأحمر.",
    },
    image: "/images/dishes/carving-station.webp",
    servingStyle: "tableside",
    tags: ["hot", "signature"],
    recommendedFor: ["weddings", "vip", "government"],
  },
  {
    id: "crepe-dessert-station",
    slug: "crepe-dessert-station",
    categoryId: "live-stations",
    name: { en: "Crepe Dessert Station", ar: "محطة الكريب الحلو" },
    description: {
      en: "Thin crepes folded around Nutella, fresh berries, mango, cream and toasted nuts.",
      ar: "كريب رقيق محشو بالنوتيلا والتوت الطازج والمانجو والكريمة والمكسرات.",
    },
    image: "/images/dishes/crepe-dessert-station.webp",
    servingStyle: "station",
    tags: ["vegetarian", "hot"],
    recommendedFor: ["birthdays", "weddings", "private"],
  },
  {
    id: "mocktail-station",
    slug: "mocktail-station",
    categoryId: "live-stations",
    name: { en: "Mocktail & Refresher Station", ar: "محطة المشروبات المنعشة" },
    description: {
      en: "Mojito virgin, passion-mint, watermelon-rose and Saudi champagne — mixed to order.",
      ar: "موهيتو خالٍ من الكحول، باشن نعناع، بطيخ-ورد، وشمبانيا سعودية — تُمزج طلباً.",
    },
    image: "/images/dishes/mocktail-station.webp",
    servingStyle: "station",
    tags: ["vegan", "cold"],
    recommendedFor: ["weddings", "vip", "corporate", "private"],
  },
  {
    id: "mini-dessert-action-station",
    slug: "mini-dessert-action-station",
    categoryId: "live-stations",
    name: { en: "Mini Dessert Action Station", ar: "محطة الحلويات المصغرة" },
    description: {
      en: "Chocolate fondue, churros to order, mini éclairs and rotating chef's specialty.",
      ar: "فوندو الشوكولاتة، تشورو طلباً، إكلير صغير وحلوى الشيف المتغيرة.",
    },
    image: "/images/dishes/mini-dessert-action-station.webp",
    servingStyle: "station",
    tags: ["vegetarian", "hot"],
    recommendedFor: ["birthdays", "weddings"],
  },

  /* ─── BBQ ──────────────────────────────────────────────────────────── */
  {
    id: "lamb-ouzal",
    slug: "lamb-ouzal",
    categoryId: "bbq",
    name: { en: "Lamb Ouzal", ar: "أوزال الخروف" },
    description: {
      en: "Tender lamb chunks marinated in Levantine spices and grilled over charcoal.",
      ar: "قطع خروف طرية متبّلة بالبهارات الشامية ومشوية على الفحم.",
    },
    image: "/images/dishes/lamb-ouzal.webp",
    servingStyle: "buffet",
    tags: ["hot", "signature", "saudi"],
    recommendedFor: ["weddings", "private", "ramadan-eid"],
    signature: true,
  },
  {
    id: "lamb-kebab",
    slug: "lamb-kebab",
    categoryId: "bbq",
    name: { en: "Lamb Kebab", ar: "كباب لحم الخروف" },
    description: {
      en: "Hand-minced lamb with onion, parsley and sumac — skewered and char-grilled.",
      ar: "لحم خروف مفروم يدوياً مع البصل والبقدونس والسماق — على أسياخ ومشوي على الفحم.",
    },
    image: "/images/dishes/lamb-kebab.webp",
    servingStyle: "buffet",
    tags: ["hot", "saudi"],
    recommendedFor: ["weddings", "private", "ramadan-eid"],
  },
  {
    id: "shish-tawook-red",
    slug: "shish-tawook-red",
    categoryId: "bbq",
    name: { en: "Red Shish Tawook", ar: "شيش طاووق أحمر" },
    description: {
      en: "Chicken cubes marinated in tomato, paprika and garlic — grilled until juicy.",
      ar: "مكعبات دجاج متبّلة بالطماطم والفلفل الحلو والثوم — مشوية حتى تكون عصارية.",
    },
    image: "/images/dishes/shish-tawook-red.webp",
    servingStyle: "buffet",
    tags: ["hot"],
    recommendedFor: ["weddings", "corporate", "private", "ramadan-eid"],
  },
  {
    id: "shish-tawook-white",
    slug: "shish-tawook-white",
    categoryId: "bbq",
    name: { en: "White Shish Tawook", ar: "شيش طاووق أبيض" },
    description: {
      en: "Yogurt-marinated chicken with lemon, garlic and white pepper — grilled and finished with toum.",
      ar: "دجاج متبّل باللبن مع الليمون والثوم والفلفل الأبيض — مشوي ويُقدَّم بالثومية.",
    },
    image: "/images/dishes/shish-tawook-white.webp",
    servingStyle: "buffet",
    tags: ["hot"],
    recommendedFor: ["weddings", "corporate", "private"],
  },
  {
    id: "chicken-tikka",
    slug: "chicken-tikka",
    categoryId: "bbq",
    name: { en: "Chicken Tikka", ar: "تكا الدجاج" },
    description: {
      en: "Tandoor-style chicken marinated in yogurt, ginger and garam masala.",
      ar: "دجاج على طريقة التندور متبّل باللبن والزنجبيل وغرام ماسالا.",
    },
    image: "/images/dishes/chicken-tikka.webp",
    servingStyle: "buffet",
    tags: ["hot", "spicy"],
    recommendedFor: ["weddings", "private", "corporate"],
  },
  {
    id: "chicken-kebab",
    slug: "chicken-kebab",
    categoryId: "bbq",
    name: { en: "Chicken Kebab", ar: "كباب الدجاج" },
    description: {
      en: "Hand-minced chicken kebabs with shallot, coriander and warm spices.",
      ar: "كباب دجاج مفروم يدوياً مع الكراث والكزبرة والبهارات الدافئة.",
    },
    image: "/images/dishes/chicken-kebab.webp",
    servingStyle: "buffet",
    tags: ["hot"],
    recommendedFor: ["weddings", "private", "ramadan-eid"],
  },
  {
    id: "lamb-neck-ribs",
    slug: "lamb-neck-ribs",
    categoryId: "bbq",
    name: { en: "Lamb Neck Ribs", ar: "أضلاع رقبة الخروف" },
    description: {
      en: "Slow-marinated lamb neck ribs grilled over charcoal — fall-off-the-bone tender.",
      ar: "أضلاع رقبة خروف متبّلة طويلاً ومشوية على الفحم — طرية بشكل استثنائي.",
    },
    image: "/images/dishes/lamb-neck-ribs.webp",
    servingStyle: "buffet",
    tags: ["hot", "signature"],
    recommendedFor: ["weddings", "private", "ramadan-eid", "vip"],
  },
  {
    id: "lamb-arayes",
    slug: "lamb-arayes",
    categoryId: "bbq",
    name: { en: "Lamb Arayes", ar: "عرايس اللحم" },
    description: {
      en: "Pita bread stuffed with spiced lamb mince, grilled until crisp on the outside, juicy within.",
      ar: "خبز عربي محشو بلحم خروف متبّل، مشوي حتى يصبح مقرمشاً من الخارج وعصارياً من الداخل.",
    },
    image: "/images/dishes/lamb-arayes.webp",
    servingStyle: "buffet",
    tags: ["hot", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "private"],
  },
  {
    id: "grilled-fish-steak",
    slug: "grilled-fish-steak",
    categoryId: "bbq",
    name: { en: "Grilled Fish Steak", ar: "شريحة سمك مشوية" },
    description: {
      en: "Hamour or grouper steaks marinated in lemon, chilli and herbs — char-grilled.",
      ar: "شرائح هامور أو نوع مماثل متبّلة بالليمون والفلفل والأعشاب — مشوية على الفحم.",
    },
    image: "/images/dishes/grilled-fish-steak.webp",
    servingStyle: "buffet",
    tags: ["hot", "seafood"],
    recommendedFor: ["weddings", "vip", "private"],
  },
  {
    id: "grilled-chicken-leg",
    slug: "grilled-chicken-leg",
    categoryId: "bbq",
    name: { en: "Grilled Chicken Leg", ar: "فخذ دجاج مشوي" },
    description: {
      en: "Whole chicken legs marinated overnight in yogurt and Saudi spices, served with grilled corn.",
      ar: "أفخاذ دجاج متبّلة طوال الليل باللبن والبهارات السعودية، تُقدَّم مع الذرة المشوية.",
    },
    image: "/images/dishes/grilled-chicken-leg.webp",
    servingStyle: "buffet",
    tags: ["hot", "saudi"],
    recommendedFor: ["private", "birthdays", "ramadan-eid"],
  },
  {
    id: "beef-burger-grilled",
    slug: "beef-burger-grilled",
    categoryId: "bbq",
    name: { en: "Grilled Beef Burger", ar: "برغر اللحم المشوي" },
    description: {
      en: "Char-grilled beef patty in a brioche bun with cheddar, lettuce and house sauce.",
      ar: "قطعة لحم بقر مشوية على الفحم في خبز البريوش مع شيدر وخس وصلصة خاصة.",
    },
    image: "/images/dishes/beef-burger-grilled.webp",
    servingStyle: "buffet",
    tags: ["hot", "international"],
    recommendedFor: ["birthdays", "private", "corporate"],
  },
  {
    id: "fish-sabach-grilled",
    slug: "fish-sabach-grilled",
    categoryId: "bbq",
    name: { en: "Grilled Fish Sabach", ar: "سمك صباح مشوي" },
    description: {
      en: "Whole sabach fish grilled with garlic, coriander and chilli — served with tahini and rocket.",
      ar: "سمك صباح كامل مشوي بالثوم والكزبرة والفلفل — يُقدَّم مع الطحينة والجرجير.",
    },
    image: "/images/dishes/fish-sabach-grilled.webp",
    servingStyle: "buffet",
    tags: ["hot", "seafood", "saudi"],
    recommendedFor: ["weddings", "private", "ramadan-eid"],
  },

  /* ─── EASTERN CUISINE ──────────────────────────────────────────────── */
  {
    id: "classic-hummus-tahini",
    slug: "classic-hummus-tahini",
    categoryId: "eastern",
    name: { en: "Classic Hummus with Tahini", ar: "حمص بالطحينة" },
    description: {
      en: "Smooth chickpea hummus topped with extra-virgin olive oil, sumac and toasted pine nuts.",
      ar: "حمص ناعم مع زيت زيتون بكر ممتاز وسماق وصنوبر محمّص.",
    },
    image: "/images/dishes/classic-hummus-tahini.webp",
    servingStyle: "buffet",
    tags: ["vegan", "cold", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "corporate", "private"],
  },
  {
    id: "spicy-labneh-nuts",
    slug: "spicy-labneh-nuts",
    categoryId: "eastern",
    name: { en: "Spicy Labneh with Mixed Nuts", ar: "لبنة حارة بالمكسرات" },
    description: {
      en: "Strained yogurt with Aleppo pepper, garlic confit and a crown of crushed nuts.",
      ar: "لبنة مصفّاة مع فلفل حلبي وثوم مكنفت ومكسرات مكسّرة.",
    },
    image: "/images/dishes/spicy-labneh-nuts.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold", "spicy", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "private"],
  },
  {
    id: "muhammara-eggplant",
    slug: "muhammara-eggplant",
    categoryId: "eastern",
    name: { en: "Muhammara with Eggplant", ar: "محمرة بالباذنجان" },
    description: {
      en: "Roasted red pepper and walnut dip with pomegranate molasses, served beside smoky eggplant.",
      ar: "غموس الفلفل الأحمر المشوي والجوز مع دبس الرمان، يُقدَّم بجانب الباذنجان المدخن.",
    },
    image: "/images/dishes/muhammara-eggplant.webp",
    servingStyle: "buffet",
    tags: ["vegan", "cold", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "private"],
  },
  {
    id: "falafel-millefeuille",
    slug: "falafel-millefeuille",
    categoryId: "eastern",
    name: { en: "Falafel Mille-Feuille", ar: "فلافل ميل فوي" },
    description: {
      en: "Modernist falafel layered with tahini cream and quick-pickled vegetables.",
      ar: "فلافل بطريقة حديثة بطبقات كريمة الطحينة والخضار المخللة.",
    },
    image: "/images/dishes/falafel-millefeuille.webp",
    servingStyle: "buffet",
    tags: ["vegan", "hot", "signature", "saudi"],
    recommendedFor: ["weddings", "corporate", "private"],
  },
  {
    id: "shawarma-beetroot-rice",
    slug: "shawarma-beetroot-rice",
    categoryId: "eastern",
    name: { en: "Shawarma with Beetroot Rice", ar: "شاورما مع أرز الشمندر" },
    description: {
      en: "Spit-roasted shawarma served on jewel-toned beetroot rice with toum and pickles.",
      ar: "شاورما مشوية تُقدَّم فوق أرز الشمندر الزاهي مع الثومية والمخللات.",
    },
    image: "/images/dishes/shawarma-beetroot-rice.webp",
    servingStyle: "buffet",
    tags: ["hot", "saudi"],
    recommendedFor: ["weddings", "private", "ramadan-eid"],
  },
  {
    id: "mansaf-meat",
    slug: "mansaf-meat",
    categoryId: "eastern",
    name: { en: "Mansaf with Lamb", ar: "منسف باللحم" },
    description: {
      en: "Levantine national dish — slow-cooked lamb in fermented yogurt jameed over saffron rice.",
      ar: "الطبق الوطني الشامي — لحم خروف مطهو ببطء في الجميد فوق أرز الزعفران.",
    },
    image: "/images/dishes/mansaf-meat.webp",
    servingStyle: "buffet",
    tags: ["hot", "signature", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "government"],
    signature: true,
  },
  {
    id: "matbooz-meat",
    slug: "matbooz-meat",
    categoryId: "eastern",
    name: { en: "Madbous with Lamb", ar: "مدبوس باللحم" },
    description: {
      en: "Saudi spiced rice (madbous) with slow-braised lamb, raisins and dried lime.",
      ar: "أرز سعودي متبّل (مدبوس) مع لحم خروف مطهو ببطء، زبيب ولومي مجفف.",
    },
    image: "/images/dishes/matbooz-meat.webp",
    servingStyle: "buffet",
    tags: ["hot", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "government", "private"],
  },
  {
    id: "maklouba-chicken",
    slug: "maklouba-chicken",
    categoryId: "eastern",
    name: { en: "Maqluba with Chicken", ar: "مقلوبة بالدجاج" },
    description: {
      en: "Layered rice with chicken, eggplant and cauliflower — inverted at the table.",
      ar: "أرز بطبقات مع الدجاج والباذنجان والقرنبيط — تُقلب على المائدة.",
    },
    image: "/images/dishes/maklouba-chicken.webp",
    servingStyle: "tableside",
    tags: ["hot", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "private"],
  },
  {
    id: "kebbeh-yogurt-coriander",
    slug: "kebbeh-yogurt-coriander",
    categoryId: "eastern",
    name: { en: "Kibbeh in Yogurt-Coriander Sauce", ar: "كبة باللبن والكزبرة" },
    description: {
      en: "Hand-rolled bulgur kibbeh poached in warm yogurt with garlic and coriander.",
      ar: "كبة برغل ملفوفة يدوياً مسلوقة في اللبن الدافئ مع الثوم والكزبرة.",
    },
    image: "/images/dishes/kebbeh-yogurt-coriander.webp",
    servingStyle: "buffet",
    tags: ["hot", "saudi"],
    recommendedFor: ["ramadan-eid", "weddings", "private"],
  },
  {
    id: "chicken-biryani-raita",
    slug: "chicken-biryani-raita",
    categoryId: "eastern",
    name: { en: "Chicken Biryani with Raita", ar: "برياني الدجاج مع الريتا" },
    description: {
      en: "Fragrant basmati layered with marinated chicken, saffron and crispy onion — served with mint raita.",
      ar: "بسمتي عطري بطبقات مع دجاج متبّل وزعفران وبصل مقرمش — يُقدَّم مع ريتا النعناع.",
    },
    image: "/images/dishes/chicken-biryani-raita.webp",
    servingStyle: "buffet",
    tags: ["hot", "spicy"],
    recommendedFor: ["weddings", "ramadan-eid", "private", "corporate"],
  },
  {
    id: "mixed-stuffed-vegetables",
    slug: "mixed-stuffed-vegetables",
    categoryId: "eastern",
    name: { en: "Mixed Stuffed Vegetables", ar: "خضار محشية مشكلة" },
    description: {
      en: "Vine leaves, courgette and aubergine stuffed with rice, lamb and herbs — slow-cooked in pomegranate broth.",
      ar: "ورق عنب وكوسا وباذنجان محشي بالأرز واللحم والأعشاب — مطهو ببطء في مرق الرمان.",
    },
    image: "/images/dishes/mixed-stuffed-vegetables.webp",
    servingStyle: "buffet",
    tags: ["hot", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "private"],
  },
  {
    id: "fattoush-pomegranate",
    slug: "fattoush-pomegranate",
    categoryId: "eastern",
    name: { en: "Fattoush with Pomegranate Molasses", ar: "فتوش بدبس الرمان" },
    description: {
      en: "Crisp romaine, tomato, cucumber, radish and toasted khobz with sumac-pomegranate dressing.",
      ar: "خس مقرمش وطماطم وخيار وفجل وخبز محمّص مع صلصة السماق والرمان.",
    },
    image: "/images/dishes/fattoush-pomegranate.webp",
    servingStyle: "buffet",
    tags: ["vegan", "cold", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "private", "corporate"],
  },
  {
    id: "tabbouleh-quinoa",
    slug: "tabbouleh-quinoa",
    categoryId: "eastern",
    name: { en: "Tabbouleh with Quinoa", ar: "تبولة الكينوا" },
    description: {
      en: "Levantine parsley salad with quinoa instead of bulgur — bright, lemony, full of herbs.",
      ar: "سلطة البقدونس الشامية بالكينوا بدلاً من البرغل — منعشة بالليمون والأعشاب.",
    },
    image: "/images/dishes/tabbouleh-quinoa.webp",
    servingStyle: "buffet",
    tags: ["vegan", "cold", "gluten-free", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "corporate", "vip"],
  },
  {
    id: "saudi-jareesh",
    slug: "saudi-jareesh",
    categoryId: "eastern",
    name: { en: "Saudi Jareesh with Meat", ar: "جريش سعودي باللحم" },
    description: {
      en: "Crushed wheat porridge slow-cooked with lamb, yogurt and Bedouin spices.",
      ar: "حبوب القمح المجروشة مطهوة ببطء مع لحم الخروف واللبن وبهارات بدوية.",
    },
    image: "/images/dishes/saudi-jareesh.webp",
    servingStyle: "buffet",
    tags: ["hot", "saudi", "signature"],
    recommendedFor: ["ramadan-eid", "weddings", "government"],
  },

  /* ─── ITALIAN CUISINE ──────────────────────────────────────────────── */
  {
    id: "linguine-al-pesto-chicken",
    slug: "linguine-al-pesto-chicken",
    categoryId: "italian",
    name: { en: "Linguine al Pesto with Chicken", ar: "لينغويني بالبيستو والدجاج" },
    description: {
      en: "Fresh linguine tossed in basil-pine pesto with grilled chicken and shaved parmesan.",
      ar: "لينغويني طازج مع بيستو الريحان والصنوبر، دجاج مشوي وبارميزان مبشور.",
    },
    image: "/images/dishes/linguine-al-pesto-chicken.webp",
    servingStyle: "buffet",
    tags: ["hot", "international"],
    recommendedFor: ["weddings", "corporate", "private"],
  },
  {
    id: "seafood-lasagna",
    slug: "seafood-lasagna",
    categoryId: "italian",
    name: { en: "Seafood Lasagna", ar: "لازانيا بالمأكولات البحرية" },
    description: {
      en: "Layers of fresh pasta, shrimp, calamari and white fish in a delicate béchamel-cream sauce.",
      ar: "طبقات معكرونة طازجة مع روبيان وكاليماري وسمك أبيض في صلصة بشاميل-كريمة رقيقة.",
    },
    image: "/images/dishes/seafood-lasagna.webp",
    servingStyle: "buffet",
    tags: ["hot", "seafood", "signature"],
    recommendedFor: ["weddings", "vip", "corporate"],
  },
  {
    id: "caprese-tomato-pesto",
    slug: "caprese-tomato-pesto",
    categoryId: "italian",
    name: { en: "Caprese with Tomato & Pesto", ar: "كابريزي بالطماطم والبيستو" },
    description: {
      en: "Heritage tomato, buffalo mozzarella, basil and a generous swirl of fresh pesto.",
      ar: "طماطم تراثية وموزاريلا الجاموس وريحان مع لمسة سخية من البيستو الطازج.",
    },
    image: "/images/dishes/caprese-tomato-pesto.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold", "international"],
    recommendedFor: ["corporate", "weddings", "vip"],
  },
  {
    id: "burrata-prosciutto",
    slug: "burrata-prosciutto",
    categoryId: "italian",
    name: { en: "Burrata with Smoked Beef Bresaola", ar: "بوراتا مع لحم البقر المدخن (بريزاولا)" },
    description: {
      en: "Creamy burrata served with smoked beef bresaola, rocket leaves and a drizzle of aged balsamic.",
      ar: "بوراتا كريمي مع شرائح لحم البقر المدخن (بريزاولا)، جرجير ولمسة من الخل البلسمي المعتّق.",
    },
    image: "/images/dishes/burrata-prosciutto.webp",
    servingStyle: "plated",
    tags: ["cold", "signature", "international"],
    recommendedFor: ["vip", "weddings"],
    signature: true,
  },
  {
    id: "risotto-funghi",
    slug: "risotto-funghi",
    categoryId: "italian",
    name: { en: "Risotto ai Funghi", ar: "ريزوتو الفطر" },
    description: {
      en: "Arborio rice slow-stirred with wild mushroom, herb-infused broth and aged parmesan.",
      ar: "أرز أربوريو مطبوخ ببطء مع الفطر البري ومرق الأعشاب وبارميزان معتّق.",
    },
    image: "/images/dishes/risotto-funghi.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "hot", "international"],
    recommendedFor: ["weddings", "corporate", "vip"],
  },
  {
    id: "arancini-classic",
    slug: "arancini-classic",
    categoryId: "italian",
    name: { en: "Classic Arancini", ar: "أرانشيني كلاسيكي" },
    description: {
      en: "Saffron rice balls stuffed with ragù and mozzarella, breaded and fried golden.",
      ar: "كرات أرز بالزعفران محشوة بالراغو والموزاريلا، مغلفة بفتات الخبز ومقلية حتى الذهبي.",
    },
    image: "/images/dishes/arancini-classic.webp",
    servingStyle: "passed",
    tags: ["hot", "international"],
    recommendedFor: ["corporate", "weddings", "private"],
  },
  {
    id: "beef-carpaccio",
    slug: "beef-carpaccio",
    categoryId: "italian",
    name: { en: "Beef Carpaccio", ar: "كارباتشو لحم البقر" },
    description: {
      en: "Whisper-thin beef tenderloin with rocket, parmesan, capers and lemon-olive oil.",
      ar: "شرائح رفيعة جداً من خاصرة لحم البقر مع جرجير وبارميزان وكبر وزيت ليمون.",
    },
    image: "/images/dishes/beef-carpaccio.webp",
    servingStyle: "plated",
    tags: ["cold", "signature"],
    recommendedFor: ["vip", "weddings"],
  },
  {
    id: "margherita-flatbread",
    slug: "margherita-flatbread",
    categoryId: "italian",
    name: { en: "Margherita Flatbread", ar: "فطيرة مارغريتا" },
    description: {
      en: "Wood-fired stone-baked flatbread with San Marzano tomato, fior di latte and torn basil.",
      ar: "فطيرة على الحطب من حجر الفرن مع طماطم سان مارزانو وفيور دي لاتي وريحان.",
    },
    image: "/images/dishes/margherita-flatbread.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "hot", "international"],
    recommendedFor: ["birthdays", "private", "corporate"],
  },
  {
    id: "spaghetti-aglio-olio",
    slug: "spaghetti-aglio-olio",
    categoryId: "italian",
    name: { en: "Spaghetti Aglio e Olio", ar: "سباغيتي الثوم والزيت" },
    description: {
      en: "Spaghetti tossed with garlic, chilli, parsley and extra-virgin olive oil — pure simplicity.",
      ar: "سباغيتي مع الثوم والفلفل والبقدونس وزيت زيتون بكر ممتاز — البساطة في أعلى مستوياتها.",
    },
    image: "/images/dishes/spaghetti-aglio-olio.webp",
    servingStyle: "buffet",
    tags: ["vegan", "hot", "international"],
    recommendedFor: ["corporate", "private"],
  },
  {
    id: "focaccia-rosemary",
    slug: "focaccia-rosemary",
    categoryId: "italian",
    name: { en: "Rosemary Focaccia", ar: "فوكاتشيا بإكليل الجبل" },
    description: {
      en: "Pillowy focaccia baked with rosemary, sea salt and a drizzle of olive oil.",
      ar: "فوكاتشيا طرية مخبوزة بإكليل الجبل وملح البحر ولمسة زيت زيتون.",
    },
    image: "/images/dishes/focaccia-rosemary.webp",
    servingStyle: "buffet",
    tags: ["vegan", "hot", "international"],
    recommendedFor: ["corporate", "weddings", "private"],
  },
  {
    id: "tiramisu-classico",
    slug: "tiramisu-classico",
    categoryId: "italian",
    name: { en: "Tiramisù Classico", ar: "تيراميسو كلاسيكي" },
    description: {
      en: "Mascarpone cream layered with coffee-soaked savoiardi, finished with a dusting of bitter cocoa.",
      ar: "كريمة الماسكاربوني بطبقات مع سافوياردي مغمّس بالقهوة ورشة من الكاكاو المر.",
    },
    image: "/images/dishes/tiramisu-classico.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold", "international"],
    recommendedFor: ["weddings", "corporate", "vip"],
  },
  {
    id: "panna-cotta-berries",
    slug: "panna-cotta-berries",
    categoryId: "italian",
    name: { en: "Vanilla Panna Cotta with Berries", ar: "بانا كوتا بالفانيليا والتوت" },
    description: {
      en: "Silken cream-vanilla pudding crowned with macerated seasonal berries.",
      ar: "بودينغ الكريمة والفانيليا الحريري مع توت موسمي منقوع.",
    },
    image: "/images/dishes/panna-cotta-berries.webp",
    servingStyle: "plated",
    tags: ["vegetarian", "cold", "international"],
    recommendedFor: ["weddings", "vip"],
  },

  /* ─── SEAFOOD & SUSHI ──────────────────────────────────────────────── */
  {
    id: "grilled-hamour-herbs",
    slug: "grilled-hamour-herbs",
    categoryId: "seafood-sushi",
    name: { en: "Grilled Hamour with Herbs", ar: "هامور مشوي بالأعشاب" },
    description: {
      en: "Red Sea hamour fillet grilled with thyme, garlic and saffron butter.",
      ar: "فيليه هامور من البحر الأحمر مشوي مع الزعتر والثوم وزبدة الزعفران.",
    },
    image: "/images/dishes/grilled-hamour-herbs.webp",
    servingStyle: "buffet",
    tags: ["hot", "seafood", "signature", "saudi"],
    recommendedFor: ["weddings", "vip", "private"],
    signature: true,
  },
  {
    id: "tandoori-prawns",
    slug: "tandoori-prawns",
    categoryId: "seafood-sushi",
    name: { en: "Tandoori Prawns", ar: "روبيان تندوري" },
    description: {
      en: "Jumbo prawns marinated in yogurt, ginger and chilli, fired in a tandoor oven.",
      ar: "روبيان جامبو متبّل باللبن والزنجبيل والفلفل، مطهو في فرن التندور.",
    },
    image: "/images/dishes/tandoori-prawns.webp",
    servingStyle: "buffet",
    tags: ["hot", "seafood", "spicy"],
    recommendedFor: ["weddings", "vip", "private"],
  },
  {
    id: "fish-rolls-lemon",
    slug: "fish-rolls-lemon",
    categoryId: "seafood-sushi",
    name: { en: "Fish Rolls in Lemon Sauce", ar: "لفائف السمك بصلصة الليمون" },
    description: {
      en: "Pan-seared fish rolls finished in lemon-butter and caper sauce.",
      ar: "لفائف سمك مشوية في المقلاة مع صلصة الليمون والزبدة والكبر.",
    },
    image: "/images/dishes/fish-rolls-lemon.webp",
    servingStyle: "buffet",
    tags: ["hot", "seafood"],
    recommendedFor: ["weddings", "corporate", "vip"],
  },
  {
    id: "salmon-sushi-cake",
    slug: "salmon-sushi-cake",
    categoryId: "seafood-sushi",
    name: { en: "Salmon Sushi Cake", ar: "كيكة السوشي بالسلمون" },
    description: {
      en: "Layered sushi rice and fresh salmon constructed as a celebration cake, topped with avocado and roe.",
      ar: "أرز سوشي بطبقات مع سلمون طازج على شكل كعكة احتفالية، مع أفوكادو وبيض السمك.",
    },
    image: "/images/dishes/salmon-sushi-cake.webp",
    servingStyle: "tableside",
    tags: ["cold", "seafood", "signature"],
    recommendedFor: ["weddings", "vip", "birthdays"],
    signature: true,
  },
  {
    id: "california-rolls",
    slug: "california-rolls",
    categoryId: "seafood-sushi",
    name: { en: "California Rolls", ar: "رولات كاليفورنيا" },
    description: {
      en: "Inside-out rolls with crab stick, avocado and cucumber, finished with sesame seeds.",
      ar: "رولات من الداخل إلى الخارج مع سرطان البحر والأفوكادو والخيار، مع بذور السمسم.",
    },
    image: "/images/dishes/california-rolls.webp",
    servingStyle: "buffet",
    tags: ["cold", "seafood"],
    recommendedFor: ["weddings", "corporate", "vip", "birthdays"],
  },
  {
    id: "spicy-tuna-rolls",
    slug: "spicy-tuna-rolls",
    categoryId: "seafood-sushi",
    name: { en: "Spicy Tuna Rolls", ar: "رولات التونة الحارة" },
    description: {
      en: "Diced tuna with sriracha-mayo, cucumber and spring onion in nori.",
      ar: "تونة مقطّعة مع صلصة السريراتشا-مايو والخيار والبصل الأخضر في النوري.",
    },
    image: "/images/dishes/spicy-tuna-rolls.webp",
    servingStyle: "buffet",
    tags: ["cold", "seafood", "spicy"],
    recommendedFor: ["corporate", "vip", "private"],
  },
  {
    id: "dragon-rolls",
    slug: "dragon-rolls",
    categoryId: "seafood-sushi",
    name: { en: "Dragon Rolls", ar: "رولات التنين" },
    description: {
      en: "Eel and cucumber rolls draped in avocado scales with sweet eel glaze.",
      ar: "رولات الأنقليس والخيار مغلّفة بحراشف الأفوكادو مع صلصة الأنقليس الحلوة.",
    },
    image: "/images/dishes/dragon-rolls.webp",
    servingStyle: "buffet",
    tags: ["cold", "seafood", "signature"],
    recommendedFor: ["vip", "weddings"],
  },
  {
    id: "tofu-spring-rolls",
    slug: "tofu-spring-rolls",
    categoryId: "seafood-sushi",
    name: { en: "Fresh Tofu Spring Rolls", ar: "لفائف التوفو الطازجة" },
    description: {
      en: "Rice paper rolls with silken tofu, julienned vegetables and Thai basil — sweet-chilli dip.",
      ar: "لفائف ورق الأرز مع توفو حريري وخضار مقطّعة وريحان تايلاندي — مع غموس الفلفل الحلو.",
    },
    image: "/images/dishes/tofu-spring-rolls.webp",
    servingStyle: "buffet",
    tags: ["vegan", "cold", "gluten-free"],
    recommendedFor: ["corporate", "vip", "private"],
  },
  {
    id: "shrimp-cocktail",
    slug: "shrimp-cocktail",
    categoryId: "seafood-sushi",
    name: { en: "Classic Shrimp Cocktail", ar: "كوكتيل الروبيان الكلاسيكي" },
    description: {
      en: "Poached jumbo shrimp on crushed ice with classic marie-rose sauce and lemon.",
      ar: "روبيان جامبو مسلوق على الثلج المجروش مع صلصة ماري-روز الكلاسيكية والليمون.",
    },
    image: "/images/dishes/shrimp-cocktail.webp",
    servingStyle: "buffet",
    tags: ["cold", "seafood"],
    recommendedFor: ["weddings", "vip", "corporate"],
  },
  {
    id: "crab-mango-sesame-salad",
    slug: "crab-mango-sesame-salad",
    categoryId: "seafood-sushi",
    name: { en: "Crab & Mango Salad with Sesame", ar: "سلطة سرطان البحر والمانجو بالسمسم" },
    description: {
      en: "Sweet crab meat and ripe mango with toasted sesame, lime and coriander.",
      ar: "لحم سرطان البحر الحلو والمانجو الناضج مع السمسم المحمّص والليمون الأخضر والكزبرة.",
    },
    image: "/images/dishes/crab-mango-sesame-salad.webp",
    servingStyle: "buffet",
    tags: ["cold", "seafood", "signature"],
    recommendedFor: ["weddings", "vip"],
  },
  {
    id: "salmon-sashimi",
    slug: "salmon-sashimi",
    categoryId: "seafood-sushi",
    name: { en: "Salmon Sashimi", ar: "ساشيمي السلمون" },
    description: {
      en: "Premium-grade Norwegian salmon, hand-sliced and presented on shaved daikon.",
      ar: "سلمون نرويجي بدرجة ممتازة، مقطّع يدوياً ومعروض على فجل ديكون مبشور.",
    },
    image: "/images/dishes/salmon-sashimi.webp",
    servingStyle: "plated",
    tags: ["cold", "seafood", "signature", "gluten-free"],
    recommendedFor: ["vip", "weddings"],
    signature: true,
  },
  {
    id: "tuna-tartare",
    slug: "tuna-tartare",
    categoryId: "seafood-sushi",
    name: { en: "Tuna Tartare", ar: "تارتار التونة" },
    description: {
      en: "Hand-cut yellowfin tuna with avocado, soy-citrus and crispy wonton.",
      ar: "تونة يلوفن مقطّعة يدوياً مع أفوكادو وصلصة الصويا والحمضيات وونتون مقرمش.",
    },
    image: "/images/dishes/tuna-tartare.webp",
    servingStyle: "plated",
    tags: ["cold", "seafood", "signature"],
    recommendedFor: ["vip", "weddings"],
  },

  /* ─── SPECIALTY & ARABIC COFFEE ────────────────────────────────────── */
  {
    id: "saudi-qahwa-cardamom",
    slug: "saudi-qahwa-cardamom",
    categoryId: "arabic-coffee",
    name: { en: "Traditional Saudi Qahwa with Cardamom", ar: "قهوة سعودية تقليدية بالهيل" },
    description: {
      en: "Light-roast Arabian coffee infused with green cardamom — poured from the dallah.",
      ar: "قهوة عربية فاتحة التحميص بنكهة الهيل الأخضر — تُسكب من الدلّة.",
    },
    image: "/images/dishes/saudi-qahwa-cardamom.webp",
    servingStyle: "station",
    tags: ["vegan", "hot", "saudi", "signature"],
    recommendedFor: ["weddings", "ramadan-eid", "government", "vip"],
    signature: true,
  },
  {
    id: "arabic-coffee-saffron",
    slug: "arabic-coffee-saffron",
    categoryId: "arabic-coffee",
    name: { en: "Arabic Coffee with Saffron", ar: "قهوة عربية بالزعفران" },
    description: {
      en: "Premium gahwa enriched with saffron threads — golden in colour, royal in aroma.",
      ar: "قهوة فاخرة مع خيوط الزعفران — ذهبية اللون ملكية العطر.",
    },
    image: "/images/dishes/arabic-coffee-saffron.webp",
    servingStyle: "station",
    tags: ["vegan", "hot", "saudi", "signature"],
    recommendedFor: ["weddings", "ramadan-eid", "government", "vip"],
  },
  {
    id: "rose-water-coffee",
    slug: "rose-water-coffee",
    categoryId: "arabic-coffee",
    name: { en: "Rose Water Infused Coffee", ar: "قهوة بماء الورد" },
    description: {
      en: "Light Arabic coffee finished with a delicate touch of Taif rose water.",
      ar: "قهوة عربية فاتحة مع لمسة رقيقة من ماء ورد الطائف.",
    },
    image: "/images/dishes/rose-water-coffee.webp",
    servingStyle: "station",
    tags: ["vegan", "hot", "saudi"],
    recommendedFor: ["weddings", "vip", "private"],
  },
  {
    id: "gahwa-mixed-spices",
    slug: "gahwa-mixed-spices",
    categoryId: "arabic-coffee",
    name: { en: "Gahwa with Mixed Spices", ar: "قهوة بالبهارات المشكلة" },
    description: {
      en: "Traditional gahwa with cardamom, clove and cinnamon — robust and warming.",
      ar: "قهوة تقليدية بالهيل والقرنفل والقرفة — قوية ودافئة.",
    },
    image: "/images/dishes/gahwa-mixed-spices.webp",
    servingStyle: "station",
    tags: ["vegan", "hot", "saudi"],
    recommendedFor: ["ramadan-eid", "private", "government"],
  },
  {
    id: "espresso-americano",
    slug: "espresso-americano",
    categoryId: "arabic-coffee",
    name: { en: "Espresso & Americano Bar", ar: "بار الإسبريسو والأمريكانو" },
    description: {
      en: "Single-origin espresso pulled to order — also served long as Americano.",
      ar: "إسبريسو من حبوب مفردة المنشأ يُحضّر طلباً — يُقدَّم أيضاً مطوّلاً كأمريكانو.",
    },
    image: "/images/dishes/espresso-americano.webp",
    servingStyle: "station",
    tags: ["vegan", "hot"],
    recommendedFor: ["corporate", "weddings", "vip"],
  },
  {
    id: "cappuccino-latte",
    slug: "cappuccino-latte",
    categoryId: "arabic-coffee",
    name: { en: "Cappuccino & Latte", ar: "كابتشينو ولاتيه" },
    description: {
      en: "Hand-stretched milk drinks with latte art, choice of oat or almond milk on request.",
      ar: "مشروبات حليب مُحضّرة يدوياً بفن اللاتيه، مع خيار حليب الشوفان أو اللوز.",
    },
    image: "/images/dishes/cappuccino-latte.webp",
    servingStyle: "station",
    tags: ["vegetarian", "hot"],
    recommendedFor: ["corporate", "weddings", "private"],
  },
  {
    id: "specialty-cold-brew",
    slug: "specialty-cold-brew",
    categoryId: "arabic-coffee",
    name: { en: "Specialty Cold Brew", ar: "كولد برو مختص" },
    description: {
      en: "Twelve-hour slow-extracted cold brew — smooth, sweet and refreshing.",
      ar: "كولد برو مستخرج ببطء لمدة 12 ساعة — ناعم وحلو ومنعش.",
    },
    image: "/images/dishes/specialty-cold-brew.webp",
    servingStyle: "station",
    tags: ["vegan", "cold"],
    recommendedFor: ["corporate", "vip", "private"],
  },
  {
    id: "medjool-dates-selection",
    slug: "medjool-dates-selection",
    categoryId: "arabic-coffee",
    name: { en: "Medjool & Premium Dates Selection", ar: "تشكيلة تمر المجدول والتمور الفاخرة" },
    description: {
      en: "Medjool, Sukkari, Khalas and Ajwa dates — some stuffed with almond or candied orange.",
      ar: "تمر مجدول وسكري وخلاص وعجوة — بعضها محشو باللوز أو البرتقال المسكّر.",
    },
    image: "/images/dishes/medjool-dates-selection.webp",
    servingStyle: "buffet",
    tags: ["vegan", "saudi", "signature", "gluten-free"],
    recommendedFor: ["weddings", "ramadan-eid", "government", "vip"],
    signature: true,
  },
  {
    id: "baklava-assortment",
    slug: "baklava-assortment",
    categoryId: "arabic-coffee",
    name: { en: "Baklava Assortment", ar: "تشكيلة البقلاوة" },
    description: {
      en: "Filo-layered pastries with pistachio, walnut and cashew, drizzled with rose syrup.",
      ar: "معجنات فيلو بطبقات مع الفستق والجوز والكاجو، مع شراب الورد.",
    },
    image: "/images/dishes/baklava-assortment.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "vip", "government"],
  },
  {
    id: "lokum-turkish-delight",
    slug: "lokum-turkish-delight",
    categoryId: "arabic-coffee",
    name: { en: "Lokum (Turkish Delight)", ar: "ملبن (راحة)" },
    description: {
      en: "Soft Turkish delight in rose, pistachio, lemon and pomegranate flavours.",
      ar: "ملبن تركي طري بنكهات الورد والفستق والليمون والرمان.",
    },
    image: "/images/dishes/lokum-turkish-delight.webp",
    servingStyle: "buffet",
    tags: ["vegetarian"],
    recommendedFor: ["weddings", "ramadan-eid", "vip"],
  },
  {
    id: "petit-fours-selection",
    slug: "petit-fours-selection",
    categoryId: "arabic-coffee",
    name: { en: "Petit Fours Selection", ar: "تشكيلة البتي فور" },
    description: {
      en: "Miniature French pastries — éclair, opera, fruit tart, religieuse.",
      ar: "معجنات فرنسية صغيرة — إكلير، أوبرا، تارت الفواكه، ريليجيوز.",
    },
    image: "/images/dishes/petit-fours-selection.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "international"],
    recommendedFor: ["weddings", "vip", "corporate"],
  },

  /* ─── DESSERTS ─────────────────────────────────────────────────────── */
  {
    id: "mini-fruit-tarts",
    slug: "mini-fruit-tarts",
    categoryId: "desserts",
    name: { en: "Mini Fruit Tarts", ar: "تارت الفواكه الصغير" },
    description: {
      en: "Sweet pastry shells filled with vanilla crème pâtissière and crowned with glazed fresh fruit.",
      ar: "قوالب معجنات حلوة محشوّة بكريمة الفانيليا ومزيّنة بفواكه طازجة مغطّاة.",
    },
    image: "/images/dishes/mini-fruit-tarts.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold"],
    recommendedFor: ["weddings", "corporate", "birthdays"],
  },
  {
    id: "creme-brulee-cups",
    slug: "creme-brulee-cups",
    categoryId: "desserts",
    name: { en: "Crème Brûlée Cups", ar: "كاسات كريم بروليه" },
    description: {
      en: "Silky vanilla custard with a torched caramel crust, in elegant glass cups.",
      ar: "كاسترد الفانيليا الحريري مع قشرة كراميل محروقة، في كاسات زجاجية أنيقة.",
    },
    image: "/images/dishes/creme-brulee-cups.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold", "signature"],
    recommendedFor: ["weddings", "vip", "corporate"],
  },
  {
    id: "umm-ali-kunafa",
    slug: "umm-ali-kunafa",
    categoryId: "desserts",
    name: { en: "Umm Ali with Kunafa", ar: "أم علي بالكنافة" },
    description: {
      en: "Egyptian bread pudding crowned with crispy kunafa, nuts and raisins — served warm.",
      ar: "أم علي مصرية مغطّاة بالكنافة المقرمشة والمكسرات والزبيب — تُقدَّم دافئة.",
    },
    image: "/images/dishes/umm-ali-kunafa.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "hot", "signature", "saudi"],
    recommendedFor: ["ramadan-eid", "weddings", "private"],
    signature: true,
  },
  {
    id: "tiramisu-cake-square",
    slug: "tiramisu-cake-square",
    categoryId: "desserts",
    name: { en: "Tiramisù Cake Squares", ar: "مربعات كيك التيراميسو" },
    description: {
      en: "Individual portions of mascarpone and coffee-soaked sponge, dusted with cocoa.",
      ar: "حصص فردية من الماسكاربوني والإسفنج المغمّس بالقهوة، مع رشة كاكاو.",
    },
    image: "/images/dishes/tiramisu-cake-square.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold", "international"],
    recommendedFor: ["weddings", "corporate", "private"],
  },
  {
    id: "mixed-berry-cheesecake",
    slug: "mixed-berry-cheesecake",
    categoryId: "desserts",
    name: { en: "Mixed Berry Cheesecake", ar: "تشيز كيك التوت المشكل" },
    description: {
      en: "New-York baked cheesecake on biscuit base, topped with macerated mixed berries.",
      ar: "تشيز كيك نيويورك على قاعدة بسكويت، مغطّى بالتوت المشكل المنقوع.",
    },
    image: "/images/dishes/mixed-berry-cheesecake.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold"],
    recommendedFor: ["weddings", "birthdays", "corporate"],
  },
  {
    id: "passion-fruit-trifle",
    slug: "passion-fruit-trifle",
    categoryId: "desserts",
    name: { en: "Passion Fruit Trifle", ar: "تريفل الباشن فروت" },
    description: {
      en: "Layers of vanilla sponge, passion fruit curd, chantilly cream and fresh tropical fruits.",
      ar: "طبقات من الإسفنج بالفانيليا وكريمة الباشن فروت وكريمة الشانتيلي وفواكه استوائية.",
    },
    image: "/images/dishes/passion-fruit-trifle.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold"],
    recommendedFor: ["weddings", "vip", "birthdays"],
  },
  {
    id: "chocolate-cake-classic",
    slug: "chocolate-cake-classic",
    categoryId: "desserts",
    name: { en: "Classic Chocolate Cake", ar: "كيك الشوكولاتة الكلاسيكي" },
    description: {
      en: "Three-layer Belgian chocolate sponge with rich ganache and chocolate shavings.",
      ar: "إسفنج شوكولاتة بلجيكية بثلاث طبقات مع غاناش غني وقطع شوكولاتة.",
    },
    image: "/images/dishes/chocolate-cake-classic.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "signature"],
    recommendedFor: ["birthdays", "weddings", "private"],
  },
  {
    id: "mango-cake",
    slug: "mango-cake",
    categoryId: "desserts",
    name: { en: "Mango Cream Cake", ar: "كيك المانجو بالكريمة" },
    description: {
      en: "Light sponge layered with fresh mango cream and finished with mango glaze.",
      ar: "إسفنج خفيف بطبقات من كريمة المانجو الطازجة مع طبقة من المانجو.",
    },
    image: "/images/dishes/mango-cake.webp",
    servingStyle: "buffet",
    tags: ["vegetarian"],
    recommendedFor: ["weddings", "birthdays"],
  },
  {
    id: "pistachio-pudding",
    slug: "pistachio-pudding",
    categoryId: "desserts",
    name: { en: "Pistachio Pudding", ar: "مهلبية الفستق" },
    description: {
      en: "Creamy pistachio mahalabia with rosewater, topped with crushed Aleppo pistachios.",
      ar: "مهلبية فستق كريمية بماء الورد، مغطّاة بفستق حلبي مكسّر.",
    },
    image: "/images/dishes/pistachio-pudding.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold", "saudi"],
    recommendedFor: ["ramadan-eid", "weddings", "private"],
  },
  {
    id: "macarons-assortment",
    slug: "macarons-assortment",
    categoryId: "desserts",
    name: { en: "French Macarons Assortment", ar: "تشكيلة الماكرون الفرنسي" },
    description: {
      en: "Almond meringue shells in pistachio, raspberry, rose, salted caramel and chocolate.",
      ar: "قشور المرنغ باللوز بنكهات الفستق والتوت والورد والكراميل المملح والشوكولاتة.",
    },
    image: "/images/dishes/macarons-assortment.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "gluten-free", "international"],
    recommendedFor: ["weddings", "vip", "corporate", "birthdays"],
  },
  {
    id: "mini-chocolate-eclairs",
    slug: "mini-chocolate-eclairs",
    categoryId: "desserts",
    name: { en: "Mini Chocolate Éclairs", ar: "إكلير الشوكولاتة الصغير" },
    description: {
      en: "Choux pastry filled with vanilla cream and finished with dark chocolate fondant.",
      ar: "معجنات الشو محشوة بكريمة الفانيليا ومغطّاة بفوندان الشوكولاتة الداكنة.",
    },
    image: "/images/dishes/mini-chocolate-eclairs.webp",
    servingStyle: "buffet",
    tags: ["vegetarian"],
    recommendedFor: ["weddings", "corporate", "birthdays"],
  },
  {
    id: "mini-cheesecakes",
    slug: "mini-cheesecakes",
    categoryId: "desserts",
    name: { en: "Mini Cheesecakes", ar: "تشيز كيك صغير" },
    description: {
      en: "Bite-sized cheesecakes in vanilla, strawberry and lotus biscoff variants.",
      ar: "تشيز كيك بحجم اللقمة بنكهات الفانيليا والفراولة واللوتس.",
    },
    image: "/images/dishes/mini-cheesecakes.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "cold"],
    recommendedFor: ["birthdays", "weddings", "private"],
  },
  {
    id: "kunafa-trio",
    slug: "kunafa-trio",
    categoryId: "desserts",
    name: { en: "Kunafa Trio", ar: "ثلاثية الكنافة" },
    description: {
      en: "Three styles: classic cheese, Nutella-stuffed and pistachio cream — served warm with syrup.",
      ar: "ثلاثة أنواع: الجبن الكلاسيكية، محشوة بالنوتيلا، وكريمة الفستق — تُقدَّم دافئة مع القطر.",
    },
    image: "/images/dishes/kunafa-trio.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "hot", "signature", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "birthdays", "vip"],
    signature: true,
  },

  /* ─── ADDITIONS FROM AUDIT — Saudi staples ─────────────────────────── */
  {
    id: "kabsa-chicken",
    slug: "kabsa-chicken",
    categoryId: "eastern",
    name: { en: "Saudi Kabsa with Chicken", ar: "كبسة سعودية بالدجاج" },
    description: {
      en: "The Saudi national rice dish — basmati cooked with chicken, tomato, dried lime and a signature spice blend, served with a fiery shata sauce.",
      ar: "الطبق الوطني السعودي — أرز بسمتي مع الدجاج والطماطم واللومي وخلطة بهارات مميزة، يُقدَّم مع صلصة الشطة الحارة.",
    },
    image: "/images/dishes/kabsa-chicken.webp",
    servingStyle: "buffet",
    tags: ["hot", "signature", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "government", "private"],
    signature: true,
  },
  {
    id: "mandi-lamb",
    slug: "mandi-lamb",
    categoryId: "eastern",
    name: { en: "Lamb Mandi", ar: "مندي اللحم" },
    description: {
      en: "Lamb slow-cooked in an underground tandoor over fragrant smoke, served on basmati rice with raisins and toasted pine nuts.",
      ar: "لحم خروف مطهو ببطء في تنور تحت الأرض على دخان عطري، يُقدَّم على أرز البسمتي مع الزبيب والصنوبر المحمّص.",
    },
    image: "/images/dishes/mandi-lamb.webp",
    servingStyle: "buffet",
    tags: ["hot", "signature", "saudi"],
    recommendedFor: ["weddings", "ramadan-eid", "government", "private"],
    signature: true,
  },
  {
    id: "qatayef-assortment",
    slug: "qatayef-assortment",
    categoryId: "desserts",
    name: { en: "Qatayef Assortment", ar: "تشكيلة القطايف" },
    description: {
      en: "Ramadan-signature stuffed pancakes — half folded around sweet akkawi cheese, half around walnuts and cinnamon, drizzled with rosewater syrup.",
      ar: "حلويات رمضان المميزة — نصفها محشو بجبن العكاوي الحلو ونصفها بالجوز والقرفة، مع قطر ماء الورد.",
    },
    image: "/images/dishes/qatayef-assortment.webp",
    servingStyle: "buffet",
    tags: ["vegetarian", "signature", "saudi"],
    recommendedFor: ["ramadan-eid"],
    signature: true,
  },

  /* ─── ADDITIONS FROM AUDIT — VIP-grade signatures ──────────────────── */
  {
    id: "beluga-caviar-service",
    slug: "beluga-caviar-service",
    categoryId: "seafood-sushi",
    name: { en: "Beluga Caviar Service", ar: "خدمة كافيار البيلوغا" },
    description: {
      en: "Premium Beluga caviar presented on mother-of-pearl with crème fraîche, hand-made blinis and traditional accompaniments.",
      ar: "كافيار بيلوغا فاخر يُقدَّم على عرق اللؤلؤ مع كريم فريش وبليني مصنوع يدوياً ومرافقات تقليدية.",
    },
    image: "/images/dishes/beluga-caviar-service.webp",
    servingStyle: "tableside",
    tags: ["cold", "seafood", "signature"],
    recommendedFor: ["vip"],
    signature: true,
  },
  {
    id: "a5-wagyu-tasting",
    slug: "a5-wagyu-tasting",
    categoryId: "bbq",
    name: { en: "A5 Wagyu Tasting", ar: "تذوّق الواغيو A5" },
    description: {
      en: "Japanese A5 wagyu seared to order in three preparations — tataki, robata grill and shabu-shabu, finished with smoked sea salt.",
      ar: "واغيو ياباني A5 يُحمّر طلباً بثلاث طرق — تاتاكي، شواء روباتا، وشابو شابو، مع ملح البحر المدخن.",
    },
    image: "/images/dishes/a5-wagyu-tasting.webp",
    servingStyle: "tableside",
    tags: ["hot", "signature"],
    recommendedFor: ["vip"],
    signature: true,
  },
  {
    id: "white-truffle-tagliolini",
    slug: "white-truffle-tagliolini",
    categoryId: "italian",
    name: { en: "White Truffle Tagliolini", ar: "تاغليوليني بالكمأة البيضاء" },
    description: {
      en: "Hand-cut egg tagliolini in butter and aged parmesan, finished tableside with shaved Alba white truffle (in season).",
      ar: "تاغليوليني بيض مقطّع يدوياً مع زبدة وبارميزان معتّق، يُكلّل على المائدة بشرائح الكمأة البيضاء من ألبا (في الموسم).",
    },
    image: "/images/dishes/white-truffle-tagliolini.webp",
    servingStyle: "plated",
    tags: ["vegetarian", "hot", "signature"],
    recommendedFor: ["vip"],
    signature: true,
  },
];

/** All dish IDs — useful for runtime validation and tests. */
export const dishIds = dishes.map((d) => d.id);
